#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "zhenzhu",
                "name":        "大珍珠",
                "type":        "寻",
                "bonus":       85,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/zhenzhu.c",
        ]),
        ([
                "id":          "dodgebook",
                "name":        "轻功篇",
                "type":        "寻",
                "bonus":       50,
                "msg1":        "",
                "object":      "/d/yanziwu/obj/dodgebook.c",
        ]),
        ([
                "id":          "green cloth",
                "name":        "[1;32m青布衣[2;37;0m",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/green_cloth.c",
        ]),
        ([
                "id":          "bian dan",
                "name":        "熟铁扁担",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/biandan.c",
        ]),
        ([
                "id":          "tiepipa",
                "name":        "[1;36m铁琵琶[2;37;0m",
                "type":        "寻",
                "bonus":       53,
                "msg1":        "",
                "object":      "/d/guanwai/npc/obj/tiepipa.c",
        ]),
        ([
                "id":          "pink cloth",
                "name":        "粉红绸衫",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/fuzhou/obj/pink_cloth.c",
        ]),
        ([
                "id":          "pangguan bi",
                "name":        "[1;36m判官笔[2;37;0m",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/bi.c",
        ]),
        ([
                "id":          "da dao",
                "name":        "大刀",
                "type":        "寻",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/dadao.c",
        ]),
        ([
                "id":          "card1",
                "name":        "风雷堂令牌",
                "type":        "寻",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/card1.c",
        ]),
        ([
                "id":          "jian dao",
                "name":        "尖刀",
                "type":        "寻",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/jiandao.c",
        ]),
        ([
                "id":          "tongren",
                "name":        "[1;33m独脚铜人[2;37;0m",
                "type":        "寻",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/guanwai/npc/obj/tongren.c",
        ]),
        ([
                "id":          "fuchen",
                "name":        "拂尘",
                "type":        "寻",
                "bonus":       92,
                "msg1":        "",
                "object":      "/d/quanzhou/obj/fuchen.c",
        ]),
        ([
                "id":          "gebu changpao",
                "name":        "葛布长袍",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/huanghe/npc/obj/changpao.c",
        ]),
        ([
                "id":          "changjian",
                "name":        "长剑",
                "type":        "寻",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/changjian.c",
        ]),
        ([
                "id":          "zhe shan",
                "name":        "油纸折扇",
                "type":        "寻",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/zheshan.c",
        ]),
        ([
                "id":          "gan cheng",
                "name":        "杆秤",
                "type":        "寻",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/gancheng.c",
        ]),
        ([
                "id":          "fu",
                "name":        "砍柴斧",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/guiyun/npc/obj/axe.c",
        ]),
        ([
                "id":          "tie zhang",
                "name":        "[37m精铁杖[2;37;0m",
                "type":        "寻",
                "bonus":       81,
                "msg1":        "",
                "object":      "/d/tulong/yitian/npc/obj/tiezhang.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "黑色布衣",
                "type":        "寻",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/henshan/npc/obj/blackcloth.c",
        ]),
        ([
                "id":          "zijin chui",
                "name":        "紫金锤",
                "type":        "寻",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/zijinchui.c",
        ]),
        ([
                "id":          "gangzhang",
                "name":        "钢杖",
                "type":        "寻",
                "bonus":       85,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/gangzhang.c",
        ]),
        ([
                "id":          "changbian",
                "name":        "铁鞭",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/hangzhou/honghua/obj/tiebian.c",
        ]),
        ([
                "id":          "jiasha",
                "name":        "[1;33m黄色袈裟[2;37;0m",
                "type":        "寻",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/xueshan/obj/y-jiasha.c",
        ]),
        ([
                "id":          "shoufa tu1",
                "name":        "天山折梅手法图上卷",
                "type":        "寻",
                "bonus":       85,
                "msg1":        "",
                "object":      "/clone/book/zhemei_book1.c",
        ]),
        ([
                "id":          "shoufa tu2",
                "name":        "天山折梅手法图下卷",
                "type":        "寻",
                "bonus":       85,
                "msg1":        "",
                "object":      "/clone/book/zhemei_book2.c",
        ]),
        ([
                "id":          "seng mao",
                "name":        "[1;31m僧帽[2;37;0m",
                "type":        "寻",
                "bonus":       70,
                "msg1":        "",
                "object":      "/d/xueshan/obj/sengmao.c",
        ]),
        ([
                "id":          "tong bo",
                "name":        "[33m铜钹[2;37;0m",
                "type":        "寻",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/tulong/yitian/npc/obj/tongbo.c",
        ]),
        ([
                "id":          "ruanwei jia",
                "name":        "软猬甲",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/taohua/obj/ruanwei.c",
        ]),
        ([
                "id":          "pao",
                "name":        "[37m灰色道袍[2;37;0m",
                "type":        "寻",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/quanzhen/npc/obj/grayrobe.c",
        ]),
        ([
                "id":          "shan",
                "name":        "青布长衫",
                "type":        "寻",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/wudang/obj/bluecloth.c",
        ]),
        ([
                "id":          "pao",
                "name":        "青色道袍",
                "type":        "寻",
                "bonus":       92,
                "msg1":        "",
                "object":      "/d/wudang/obj/greenrobe.c",
        ]),
        ([
                "id":          "jindai",
                "name":        "束发金带",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/taohua/obj/shudai.c",
        ]),
        ([
                "id":          "pi beixin",
                "name":        "皮背心",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/city/obj/beixin.c",
        ]),
        ([
                "id":          "armor",
                "name":        "铁甲",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/city/npc/obj/tiejia.c",
        ]),
        ([
                "id":          "zhan armor",
                "name":        "战甲",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/zhanjia.c",
        ]),
        ([
                "id":          "skirt",
                "name":        "轻纱长裙",
                "type":        "寻",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/skirt.c",
        ]),
        ([
                "id":          "seng pao",
                "name":        "[1;33m僧袍[2;37;0m",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/sengpao.c",
        ]),
        ([
                "id":          "hammer",
                "name":        "铁锤",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/hammer.c",
        ]),
        ([
                "id":          "changbian",
                "name":        "长鞭",
                "type":        "寻",
                "bonus":       79,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/changbian.c",
        ]),
        ([
                "id":          "fu chen",
                "name":        "拂尘",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/fuchen.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "[1;37m白色长衫[2;37;0m",
                "type":        "寻",
                "bonus":       58,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/cloth4.c",
        ]),
        ([
                "id":          "chang pao",
                "name":        "白色长袍",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/baituo/obj/baipao.c",
        ]),
        ([
                "id":          "diao gan",
                "name":        "钓杆",
                "type":        "寻",
                "bonus":       77,
                "msg1":        "",
                "object":      "/kungfu/class/dali/obj/diaogan.c",
        ]),
});

mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
