#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "red-dress",
                "name":        "[31m霓红连衣裙[2;37;0m",
                "type":        "寻",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/red-dress.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "青布镶边袈裟",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/shaolin/obj/hui-cloth.c",
        ]),
        ([
                "id":          "panguan bi",
                "name":        "镔铁判官笔",
                "type":        "寻",
                "bonus":       81,
                "msg1":        "",
                "object":      "/d/meizhuang/npc/obj/panguan-bi.c",
        ]),
        ([
                "id":          "short blade",
                "name":        "短刀",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/yixing/npc/obj/shortblade.c",
        ]),
        ([
                "id":          "dilao key",
                "name":        "地牢钥匙",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/yaoshi.c",
        ]),
        ([
                "id":          "tiedan",
                "name":        "[1;37m铁胆[2;37;0m",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/hangzhou/honghua/obj/tiedan.c",
        ]),
        ([
                "id":          "wo dao",
                "name":        "倭刀",
                "type":        "寻",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/taiwan/npc/obj/wodao.c",
        ]),
        ([
                "id":          "jiujie bian",
                "name":        "九节鞭",
                "type":        "寻",
                "bonus":       76,
                "msg1":        "",
                "object":      "/d/yixing/npc/obj/jiujiebian.c",
        ]),
        ([
                "id":          "pi pao",
                "name":        "枣红缎面皮袍",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/heimuya/npc/obj/zaohong.c",
        ]),
        ([
                "id":          "pao",
                "name":        "白色道袍",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/wudang/obj/whiterobe.c",
        ]),
        ([
                "id":          "xionghuang",
                "name":        "雄黄",
                "type":        "寻",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/shenlong/obj/xionghuang.c",
        ]),
        ([
                "id":          "jia sha",
                "name":        "灰布镶边袈裟",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/shaolin/obj/dao-cloth.c",
        ]),
        ([
                "id":          "helan huoqiang",
                "name":        "荷兰火枪",
                "type":        "寻",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/taiwan/npc/obj/huoqiang.c",
        ]),
        ([
                "id":          "seng gun",
                "name":        "僧棍",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/xueshan/obj/senggun.c",
        ]),
        ([
                "id":          "shoes",
                "name":        "[32m绣花鞋[2;37;0m",
                "type":        "寻",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/shoes.c",
        ]),
        ([
                "id":          "shoes",
                "name":        "[32m布鞋[2;37;0m",
                "type":        "寻",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/wanjiegu/npc/obj/bu-shoes.c",
        ]),
        ([
                "id":          "hot hammer",
                "name":        "烧红的铁锤",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/village/npc/obj/hothammer.c",
        ]),
        ([
                "id":          "man dao",
                "name":        "蛮刀",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/mandao.c",
        ]),
        ([
                "id":          "junfu",
                "name":        "锦衣军服",
                "type":        "寻",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/jjunfu.c",
        ]),
        ([
                "id":          "hu pi",
                "name":        "虎皮",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/dali/npc/obj/hupi.c",
        ]),
        ([
                "id":          "pink cloth",
                "name":        "粉红绸衫",
                "type":        "寻",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/city/obj/pink_cloth.c",
        ]),
        ([
                "id":          "blade",
                "name":        "钢刀",
                "type":        "寻",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/city/obj/gangdao.c",
        ]),
        ([
                "id":          "flower shoes",
                "name":        "绣花小鞋",
                "type":        "寻",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/city/obj/flower_shoe.c",
        ]),
        ([
                "id":          "laofang key",
                "name":        "牢房钥匙",
                "type":        "寻",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/city/npc/obj/yaoshi.c",
        ]),
        ([
                "id":          "junfu",
                "name":        "军服",
                "type":        "寻",
                "bonus":       71,
                "msg1":        "",
                "object":      "/d/city/npc/obj/junfu.c",
        ]),
        ([
                "id":          "heilong bian",
                "name":        "黑龙鞭",
                "type":        "寻",
                "bonus":       71,
                "msg1":        "",
                "object":      "/d/city/npc/obj/hlbian.c",
        ]),
        ([
                "id":          "golden ring",
                "name":        "金戒指",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/city/npc/obj/goldring.c",
        ]),
        ([
                "id":          "jian",
                "name":        "钢剑",
                "type":        "寻",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/city/npc/obj/gangjian.c",
        ]),
        ([
                "id":          "flower shoes",
                "name":        "绣花小鞋",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/city/npc/obj/flower_shoe.c",
        ]),
        ([
                "id":          "changjian",
                "name":        "长剑",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/city/npc/obj/changjian.c",
        ]),
        ([
                "id":          "yayi fu",
                "name":        "衙役服",
                "type":        "寻",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/yayifu.c",
        ]),
        ([
                "id":          "sword",
                "name":        "长剑",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/sword.c",
        ]),
        ([
                "id":          "shawei bang",
                "name":        "杀威棒",
                "type":        "寻",
                "bonus":       67,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/shawei.c",
        ]),
        ([
                "id":          "sengyi",
                "name":        "僧衣",
                "type":        "寻",
                "bonus":       55,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/sengyi.c",
        ]),
        ([
                "id":          "choupao",
                "name":        "绸袍",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/choupao.c",
        ]),
        ([
                "id":          "chang pao",
                "name":        "长袍",
                "type":        "寻",
                "bonus":       59,
                "msg1":        "",
                "object":      "/d/changan/npc/obj/changpao.c",
        ]),
        ([
                "id":          "huang magua",
                "name":        "[1;33m镶边黄马褂[2;37;0m",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/goldcloth2.c",
        ]),
        ([
                "id":          "cloth",
                "name":        "布衣",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/cloth.c",
        ]),
        ([
                "id":          "duan dao",
                "name":        "短刀",
                "type":        "寻",
                "bonus":       63,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/blade2.c",
        ]),
        ([
                "id":          "gang dao",
                "name":        "[1;37m钢刀[2;37;0m",
                "type":        "寻",
                "bonus":       75,
                "msg1":        "",
                "object":      "/d/beijing/npc/obj/blade1.c",
        ]),
        ([
                "id":          "si pao",
                "name":        "青色丝袍",
                "type":        "寻",
                "bonus":       83,
                "msg1":        "",
                "object":      "/d/baituo/obj/qingpao.c",
        ]),
        ([
                "id":          "da dao",
                "name":        "大刀",
                "type":        "寻",
                "bonus":       92,
                "msg1":        "",
                "object":      "/d/baituo/obj/dadao.c",
        ]),
});

mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
