#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "abi",
                "name":        "阿碧",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/yanziwu/npc/abi.c",
        ]),
        ([
                "id":          "jin xier",
                "name":        "进喜儿",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/xier.c",
        ]),
        ([
                "id":          "caishi ren",
                "name":        "采石人",
                "type":        "杀",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/huanghe/npc/caishiren.c",
        ]),
        ([
                "id":          "piao you",
                "name":        "票友",
                "type":        "杀",
                "bonus":       76,
                "msg":        "",
                "object":      "/d/suzhou/npc/piaoyou.c",
        ]),
        ([
                "id":          "zhangyuan",
                "name":        "掌园道长",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/quanzhen/npc/zhangyuan.c",
        ]),
        ([
                "id":          "zheng biaotou",
                "name":        "郑镖头",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/fuzhou/npc/zheng.c",
        ]),
        ([
                "id":          "shi biaotou",
                "name":        "史镖头",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/fuzhou/npc/shi.c",
        ]),
        ([
                "id":          "geshiha",
                "name":        "戈什哈",
                "type":        "杀",
                "bonus":       86,
                "msg":        "",
                "object":      "/d/fuzhou/npc/geshiha.c",
        ]),
        ([
                "id":          "cui biaotou",
                "name":        "崔镖头",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/fuzhou/npc/cui.c",
        ]),
        ([
                "id":          "zhong sisao",
                "name":        "钟四嫂",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/foshan/npc/zhongsisao.c",
        ]),
        ([
                "id":          "azhu",
                "name":        "阿朱",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/yanziwu/npc/azhu.c",
        ]),
        ([
                "id":          "alamuhan",
                "name":        "阿拉木罕",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/xingxiu/npc/alamuhan.c",
        ]),
        ([
                "id":          "seng ren",
                "name":        "游方和尚",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/taishan/npc/seng-ren.c",
        ]),
        ([
                "id":          "huogong",
                "name":        "火工道人",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/quanzhen/npc/huogong.c",
        ]),
        ([
                "id":          "xixia bing",
                "name":        "西夏兵",
                "type":        "杀",
                "bonus":       73,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xixiabing.c",
        ]),
        ([
                "id":          "lao daoshi",
                "name":        "老道士",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/lingzhou/npc/laodaoshi.c",
        ]),
        ([
                "id":          "mengmianren",
                "name":        "蒙面人",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/hangzhou/npc/mengmian.c",
        ]),
        ([
                "id":          "zhuoma",
                "name":        "卓玛",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/xuedao/npc/zhuoma.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "小沙弥",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/xiaoshami.c",
        ]),
        ([
                "id":          "saodi seng",
                "name":        "扫地僧",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/shaolin/npc/saodi-seng.c",
        ]),
        ([
                "id":          "zhanggui",
                "name":        "掌柜",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hanzhong/npc/zhanggui.c",
        ]),
        ([
                "id":          "youfang daoren",
                "name":        "游方道人",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/quanzhen/npc/youfang.c",
        ]),
        ([
                "id":          "yangzong",
                "name":        "央宗",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/xuedao/npc/yangzong.c",
        ]),
        ([
                "id":          "datie seng",
                "name":        "打铁僧",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/shaolin/npc/datie-seng.c",
        ]),
        ([
                "id":          "lao heshang",
                "name":        "老和尚",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/hangzhou/npc/seng.c",
        ]),
        ([
                "id":          "bosi shangren",
                "name":        "波斯商人",
                "type":        "杀",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/xingxiu/npc/trader.c",
        ]),
        ([
                "id":          "song bing",
                "name":        "宋兵",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/xiangyang/npc/bing.c",
        ]),
        ([
                "id":          "saodi seng",
                "name":        "扫地僧",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/saodiseng.c",
        ]),
        ([
                "id":          "cheng ying",
                "name":        "程英",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/taohua/npc/cheng.c",
        ]),
        ([
                "id":          "xingzhe",
                "name":        "行者",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/shaolin/npc/xingzhe.c",
        ]),
        ([
                "id":          "zhike daozhang",
                "name":        "知客道长",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/quanzhen/npc/zhike.c",
        ]),
        ([
                "id":          "guan bing",
                "name":        "官兵",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/xingxiu/npc/bing.c",
        ]),
        ([
                "id":          "yu zu",
                "name":        "狱卒",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/shaolin/npc/yu-zu.c",
        ]),
        ([
                "id":          "xixia bing",
                "name":        "西夏兵",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/huanghe/npc/xixiabing.c",
        ]),
        ([
                "id":          "hong hua",
                "name":        "绿营会众",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/hangzhou/npc/honghua2.c",
        ]),
        ([
                "id":          "hong hua",
                "name":        "红花会众",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/hangzhou/npc/honghua1.c",
        ]),
        ([
                "id":          "seng bing",
                "name":        "守寺僧兵",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/shaolin/npc/seng-bing3.c",
        ]),
        ([
                "id":          "da han",
                "name":        "大汉",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/mingjiao/npc/menwei1.c",
        ]),
        ([
                "id":          "qiao fu",
                "name":        "樵夫",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/huanghe/npc/qiaofu.c",
        ]),
        ([
                "id":          "pihuo shang",
                "name":        "皮货商",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/guanwai/npc/pihuoshang.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "镖头",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/xiangyang/npc/biaotou.c",
        ]),
        ([
                "id":          "ya yi",
                "name":        "衙役",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/suzhou/npc/yayi.c",
        ]),
        ([
                "id":          "guan bing",
                "name":        "官兵",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/hanzhong/npc/bing.c",
        ]),
        ([
                "id":          "jieyin shi",
                "name":        "接引使",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/mingjiao/npc/jieyinshi.c",
        ]),
        ([
                "id":          "liu qin",
                "name":        "刘芹",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/henshan/npc/liuqin.c",
        ]),
        ([
                "id":          "lai fuer",
                "name":        "来福儿",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/fuer.c",
        ]),
        ([
                "id":          "zhangjing",
                "name":        "掌经道长",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/quanzhen/npc/zhangjing.c",
        ]),
        ([
                "id":          "hou yuanwai",
                "name":        "侯员外",
                "type":        "杀",
                "bonus":       73,
                "msg":        "",
                "object":      "/d/hanzhong/npc/yuanwai.c",
        ]),
        ([
                "id":          "yu fu",
                "name":        "渔夫",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/yufu.c",
        ]),
        ([
                "id":          "yangcan nu",
                "name":        "养蚕女",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/yangcannu.c",
        ]),
        ([
                "id":          "wuliang dizi",
                "name":        "无量剑弟子",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/wuliangdizi.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "乌夷商贩",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/wshangfan.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "黄衣卫士",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/weishi1.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "素衣卫士",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/weishi.c",
        ]),
        ([
                "id":          "tai jian",
                "name":        "太监",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/taijian.c",
        ]),
        ([
                "id":          "shi zhe",
                "name":        "侍者",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/shizhe.c",
        ]),
        ([
                "id":          "shi cong",
                "name":        "侍从",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/dali/npc/shicong.c",
        ]),
        ([
                "id":          "shennong dizi",
                "name":        "神农帮弟子",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/shennongdizi.c",
        ]),
        ([
                "id":          "shao nu",
                "name":        "少女",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/shaonu.c",
        ]),
        ([
                "id":          "seng ren",
                "name":        "僧人",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/dali/npc/seng.c",
        ]),
        ([
                "id":          "lie ren",
                "name":        "台夷猎人",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/dali/npc/lieshou.c",
        ]),
        ([
                "id":          "lie ren",
                "name":        "猎人",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/lieren.c",
        ]),
        ([
                "id":          "ke shang",
                "name":        "盛皮罗客商",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/keshang.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "家丁",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/jiading.c",
        ]),
        ([
                "id":          "yanghua nu",
                "name":        "养花女",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/huanu.c",
        ]),
        ([
                "id":          "gu niang",
                "name":        "台夷姑娘",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/guniang.c",
        ]),
        ([
                "id":          "gong nu",
                "name":        "宫女",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/gongnu.c",
        ]),
        ([
                "id":          "girl",
                "name":        "摆夷女子",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/girl.c",
        ]),
        ([
                "id":          "caisang nv",
                "name":        "采桑女",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/caisangnu.c",
        ]),
        ([
                "id":          "shi bing",
                "name":        "士兵",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/dali/npc/bing.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "「平通镖局」镖头",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/biaotou.c",
        ]),
        ([
                "id":          "lao zhangfang",
                "name":        "账房老夫子",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/chengdu/npc/zhangfang.c",
        ]),
        ([
                "id":          "xiao zei",
                "name":        "小贼",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/chengdu/npc/xiaozei.c",
        ]),
        ([
                "id":          "cui yingying",
                "name":        "崔莺莺",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/city/npc/yingying.c",
        ]),
        ([
                "id":          "ya yi",
                "name":        "衙役",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/city/npc/yayi.c",
        ]),
        ([
                "id":          "guan bing",
                "name":        "官兵",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/city/npc/bing.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "镖头",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/city/npc/biaotou.c",
        ]),
        ([
                "id":          "xi zi",
                "name":        "戏子",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/changan/npc/xizi.c",
        ]),
        ([
                "id":          "lao zhang",
                "name":        "老张",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/changan/npc/laozhang.c",
        ]),
        ([
                "id":          "shuoshu laoren",
                "name":        "说书老人",
                "type":        "杀",
                "bonus":       59,
                "msg":        "",
                "object":      "/d/changan/npc/laoren.c",
        ]),
        ([
                "id":          "huo ji",
                "name":        "小伙计",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/d/changan/npc/huoji.c",
        ]),
        ([
                "id":          "guan jia",
                "name":        "管家",
                "type":        "杀",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/changan/npc/guanjia.c",
        ]),
        ([
                "id":          "guan bing",
                "name":        "官兵",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/d/changan/npc/guanbing.c",
        ]),
        ([
                "id":          "flower girl",
                "name":        "卖花姑娘",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/beijing/npc/flowerg.c",
        ]),
        ([
                "id":          "zhixiang daozhang",
                "name":        "制香道长",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/wudang/zhixiang.c",
        ]),
        ([
                "id":          "zhike daozhang",
                "name":        "知客道长",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/wudang/zhike.c",
        ]),
        ([
                "id":          "shouyuan daozhang",
                "name":        "守园道长",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/wudang/shouyuan.c",
        ]),
        ([
                "id":          "qing feng",
                "name":        "清风",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/wudang/qingfeng.c",
        ]),
        ([
                "id":          "ming yue",
                "name":        "明月",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/wudang/mingyue.c",
        ]),
        ([
                "id":          "famu daozhang",
                "name":        "伐木道长",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/wudang/famu.c",
        ]),
        ([
                "id":          "xu ming",
                "name":        "虚明",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xu-ming.c",
        ]),
        ([
                "id":          "xingzhe",
                "name":        "行者",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xingzhe.c",
        ]),
        ([
                "id":          "tuobo seng",
                "name":        "托钵僧",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/tuoboseng.c",
        ]),
        ([
                "id":          "qingyuan biqiu",
                "name":        "清缘比丘",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-yuan.c",
        ]),
        ([
                "id":          "qingxiao biqiu",
                "name":        "清晓比丘",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-xiao.c",
        ]),
        ([
                "id":          "qingwu biqiu",
                "name":        "清无比丘",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wu.c",
        ]),
        ([
                "id":          "qingwen biqiu",
                "name":        "清闻比丘",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wen.c",
        ]),
        ([
                "id":          "qingwei biqiu",
                "name":        "清为比丘",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wei.c",
        ]),
        ([
                "id":          "qingshan biqiu",
                "name":        "清善比丘",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-shan.c",
        ]),
        ([
                "id":          "qingle biqiu",
                "name":        "清乐比丘",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-le.c",
        ]),
        ([
                "id":          "qingguan biqiu",
                "name":        "清观比丘",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-guan.c",
        ]),
        ([
                "id":          "qingfa biqiu",
                "name":        "清法比丘",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-fa.c",
        ]),
        ([
                "id":          "daozheng chanshi",
                "name":        "道正禅师",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-zheng.c",
        ]),
        ([
                "id":          "daoyi chanshi",
                "name":        "道一禅师",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-yi.c",
        ]),
        ([
                "id":          "daoxiang chanshi",
                "name":        "道象禅师",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-xiang2.c",
        ]),
        ([
                "id":          "daoxiang chanshi",
                "name":        "道相禅师",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-xiang.c",
        ]),
        ([
                "id":          "daopin chanshi",
                "name":        "道品禅师",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-pin.c",
        ]),
        ([
                "id":          "daojue chanshi",
                "name":        "道觉禅师",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-jue.c",
        ]),
        ([
                "id":          "daoguo chanshi",
                "name":        "道果禅师",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-guo.c",
        ]),
        ([
                "id":          "daocheng chanshi",
                "name":        "道成禅师",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-cheng.c",
        ]),
        ([
                "id":          "daochen chanshi",
                "name":        "道尘禅师",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/dao-chen.c",
        ]),
        ([
                "id":          "qiu wanjia",
                "name":        "裘万家",
                "type":        "杀",
                "bonus":       73,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/qiu-wanjia.c",
        ]),
});
mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
