#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "mi weiyi",
                "name":        "米为义",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/henshan/mi.c",
        ]),
        ([
                "id":          "qin juan",
                "name":        "秦绢",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hengshan/npc/qin.c",
        ]),
        ([
                "id":          "yi lin",
                "name":        "仪琳",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/lin.c",
        ]),
        ([
                "id":          "yi wen",
                "name":        "仪文",
                "type":        "杀",
                "bonus":       97,
                "msg":        "",
                "object":      "/kungfu/class/hengshan/wen.c",
        ]),
        ([
                "id":          "shi shuangying",
                "name":        "石双英",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/shi.c",
        ]),
        ([
                "id":          "xu tianhong",
                "name":        "徐天宏",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/xu.c",
        ]),
        ([
                "id":          "wei chunhua",
                "name":        "卫春华",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/wei.c",
        ]),
        ([
                "id":          "zhu cong",
                "name":        "朱聪",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/guiyun/npc/zhucong.c",
        ]),
        ([
                "id":          "nan xiren",
                "name":        "南希仁",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guiyun/npc/nanxiren.c",
        ]),
        ([
                "id":          "ke zhene",
                "name":        "柯镇恶",
                "type":        "杀",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/guiyun/npc/kezhene.c",
        ]),
        ([
                "id":          "han baoju",
                "name":        "韩宝驹",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guiyun/npc/hanbaoju.c",
        ]),
        ([
                "id":          "xiao yuanshan",
                "name":        "萧远山",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiaoyuanshan.c",
        ]),
        ([
                "id":          "yang chengxie",
                "name":        "杨成协",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/yang.c",
        ]),
        ([
                "id":          "zhang asheng",
                "name":        "张阿生",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/guiyun/npc/zhangasheng.c",
        ]),
        ([
                "id":          "han xiaoyin",
                "name":        "韩小莹",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/guiyun/npc/hanxiaoying.c",
        ]),
        ([
                "id":          "danqing sheng",
                "name":        "丹青生",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/meizhuang/danqing.c",
        ]),
        ([
                "id":          "zheng e",
                "name":        "郑萼",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hengshan/npc/zheng.c",
        ]),
        ([
                "id":          "li yuanzhi",
                "name":        "李沅芷",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/npc/liyuanzhi.c",
        ]),
        ([
                "id":          "hu qingyu",
                "name":        "胡庆余",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/npc/huqingyu.c",
        ]),
        ([
                "id":          "ye erniang",
                "name":        "叶二娘",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/lingzhou/npc/ye.c",
        ]),
        ([
                "id":          "xiang danian",
                "name":        "向大年",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/henshan/xiang.c",
        ]),
        ([
                "id":          "qu yang",
                "name":        "曲洋",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/riyue/qu.c",
        ]),
        ([
                "id":          "huang boliu",
                "name":        "黄伯流",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/heimuya/npc/huangboliu.c",
        ]),
        ([
                "id":          "quan jinfa",
                "name":        "全金发",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/guiyun/npc/quanjinfa.c",
        ]),
        ([
                "id":          "shi lingwei",
                "name":        "施令威",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/meizhuang/npc/shi.c",
        ]),
        ([
                "id":          "hu yuan",
                "name":        "护院",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/meizhuang/npc/huyuan.c",
        ]),
        ([
                "id":          "nanhai eshen",
                "name":        "南海鳄神",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/lingzhou/npc/nan.c",
        ]),
        ([
                "id":          "yu popo",
                "name":        "余婆婆",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/yupopo.c",
        ]),
        ([
                "id":          "ren yingying",
                "name":        "任盈盈",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/huashan/npc/ren-yingying.c",
        ]),
        ([
                "id":          "chen zhiyi",
                "name":        "陈志益",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/chen.c",
        ]),
        ([
                "id":          "cheng lingsu",
                "name":        "程灵素",
                "type":        "杀",
                "bonus":       97,
                "msg":        "",
                "object":      "/kungfu/class/hu/cheng.c",
        ]),
        ([
                "id":          "mu wanqing",
                "name":        "木婉清",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/dali/npc/muwanqing.c",
        ]),
        ([
                "id":          "xiao fei",
                "name":        "萧飞",
                "type":        "杀",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/xiaofei.c",
        ]),
        ([
                "id":          "ma wude",
                "name":        "马五德",
                "type":        "杀",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/mawude.c",
        ]),
        ([
                "id":          "long quan",
                "name":        "龙铨",
                "type":        "杀",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/longquan.c",
        ]),
        ([
                "id":          "liu hongying",
                "name":        "刘虹瑛",
                "type":        "杀",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/liuhongying.c",
        ]),
        ([
                "id":          "chen hu",
                "name":        "陈浒",
                "type":        "杀",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/chengdu/npc/chenhu.c",
        ]),
        ([
                "id":          "shi qingshan",
                "name":        "史青山",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/city/npc/shi.c",
        ]),
        ([
                "id":          "chen youde",
                "name":        "陈有德",
                "type":        "杀",
                "bonus":       97,
                "msg":        "",
                "object":      "/d/city/npc/chen.c",
        ]),
        ([
                "id":          "xiao yuanwai",
                "name":        "萧员外",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/yuanwai.c",
        ]),
        ([
                "id":          "xiangxiang",
                "name":        "湘湘",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/changan/npc/xiangxiang.c",
        ]),
        ([
                "id":          "xiao qun",
                "name":        "萧群",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/tongling2.c",
        ]),
        ([
                "id":          "zhang heng",
                "name":        "张衡",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/tongling1.c",
        ]),
        ([
                "id":          "huitong chanshi",
                "name":        "慧通禅师",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/huitong.c",
        ]),
        ([
                "id":          "dubi shenni",
                "name":        "独臂神尼",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/beijing/npc/dubi.c",
        ]),
        ([
                "id":          "ma chaoxing",
                "name":        "马超兴",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/yunlong/ma.c",
        ]),
        ([
                "id":          "kang guangling",
                "name":        "康广陵",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/kanggl.c",
        ]),
        ([
                "id":          "song qingshu",
                "name":        "宋青书",
                "type":        "杀",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/wudang/xiaosong.c",
        ]),
        ([
                "id":          "huang rong",
                "name":        "黄蓉",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/taohua/rong.c",
        ]),
        ([
                "id":          "yin zhiping",
                "name":        "尹志平",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/yin.c",
        ]),
        ([
                "id":          "zuo quan",
                "name":        "左全",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/zuo-qu.c",
        ]),
        ([
                "id":          "ma juwei",
                "name":        "马俱为",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/ma-jw.c",
        ]),
        ([
                "id":          "li futou",
                "name":        "李斧头",
                "type":        "杀",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/li-futou.c",
        ]),
        ([
                "id":          "he bujing",
                "name":        "何不净",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/he-bj.c",
        ]),
        ([
                "id":          "jingkong shitai",
                "name":        "静空师太",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/emei/kong.c",
        ]),
        ([
                "id":          "jingjia shitai",
                "name":        "静迦师太",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/kungfu/class/emei/jia.c",
        ]),
        ([
                "id":          "ji xiaofu",
                "name":        "纪晓芙",
                "type":        "杀",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/emei/ji.c",
        ]),
        ([
                "id":          "jinghui shitai",
                "name":        "静慧师太",
                "type":        "杀",
                "bonus":       93,
                "msg":        "",
                "object":      "/kungfu/class/emei/hui.c",
        ]),
        ([
                "id":          "jinghe shitai",
                "name":        "静和师太",
                "type":        "杀",
                "bonus":       62,
                "msg":        "",
                "object":      "/kungfu/class/emei/he.c",
        ]),
        ([
                "id":          "jingfeng shitai",
                "name":        "静风师太",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/emei/feng.c",
        ]),
        ([
                "id":          "jingdao shitai",
                "name":        "静道师太",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/dao.c",
        ]),
        ([
                "id":          "bei jinyi",
                "name":        "贝锦仪",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/emei/bei.c",
        ]),
        ([
                "id":          "zhu wanli",
                "name":        "褚万里",
                "type":        "杀",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/dali/chuwanli.c",
        ]),
        ([
                "id":          "zhu danchen",
                "name":        "朱丹臣",
                "type":        "杀",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/dali/zhudanchen.c",
        ]),
        ([
                "id":          "gu ducheng",
                "name":        "古笃诚",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/dali/guducheng.c",
        ]),
        ([
                "id":          "fu sigui",
                "name":        "傅思归",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/dali/fusigui.c",
        ]),
        ([
                "id":          "chu wanli",
                "name":        "褚万里",
                "type":        "杀",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/dali/chuwanli.c",
        ]),
});
mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
