#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "mu jiang",
                "name":        "木匠",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/mujiang.c",
        ]),
        ([
                "id":          "lao xiansheng",
                "name":        "老先生",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/laoxiansheng.c",
        ]),
        ([
                "id":          "jin xier",
                "name":        "进喜儿",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/xier.c",
        ]),
        ([
                "id":          "xiao fan",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taishan/npc/xiao-fan.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "小沙弥",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-ku.c",
        ]),
        ([
                "id":          "tong",
                "name":        "小道童",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/quanzhen/npc/daotong1.c",
        ]),
        ([
                "id":          "boy",
                "name":        "男孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/boy.c",
        ]),
        ([
                "id":          "xiao lan",
                "name":        "小兰",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guiyun/npc/xiaolan.c",
        ]),
        ([
                "id":          "heersu",
                "name":        "赫尔苏",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guanwai/npc/heersu.c",
        ]),
        ([
                "id":          "boy",
                "name":        "男孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/boy.c",
        ]),
        ([
                "id":          "zhang kang",
                "name":        "张康",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/foshan/npc/zhangkang.c",
        ]),
        ([
                "id":          "jinxiang ke",
                "name":        "进香客",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/emei/npc/guest.c",
        ]),
        ([
                "id":          "dizi",
                "name":        "女弟子",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/emei/npc/girldizi.c",
        ]),
        ([
                "id":          "dizi",
                "name":        "男弟子",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/emei/npc/boydizi.c",
        ]),
        ([
                "id":          "xiao lama",
                "name":        "小喇嘛",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xueshan/npc/x_lama.c",
        ]),
        ([
                "id":          "afanti",
                "name":        "阿凡提",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/xingxiu/npc/afanti.c",
        ]),
        ([
                "id":          "tiejiang",
                "name":        "铁匠",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/smith.c",
        ]),
        ([
                "id":          "laonian sengren",
                "name":        "老年僧人",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/laoniansengren.c",
        ]),
        ([
                "id":          "youke",
                "name":        "游客",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/huashan/npc/youke.c",
        ]),
        ([
                "id":          "huoji",
                "name":        "伙计",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/huanghe/npc/huoji.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/henshan/npc/xiaoer2.c",
        ]),
        ([
                "id":          "lao zhe",
                "name":        "老者",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/heimuya/npc/laozhe.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "书生",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/shu-sheng.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "tiejiang",
                "name":        "铁匠",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/smith.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "书生",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/shu-sheng.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "家丁",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/jia.c",
        ]),
        ([
                "id":          "cui",
                "name":        "小翠",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/wudang/npc/xiaocui.c",
        ]),
        ([
                "id":          "poor man",
                "name":        "穷汉",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/poorman.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "药铺伙计",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/huoji.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "小沙弥",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-bei.c",
        ]),
        ([
                "id":          "girl",
                "name":        "女孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/quanzhou/npc/girl.c",
        ]),
        ([
                "id":          "you ke",
                "name":        "游客",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/quanzhen/npc/youke.c",
        ]),
        ([
                "id":          "dibao",
                "name":        "地保",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/hanzhong/npc/dibao.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer3.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "girl",
                "name":        "女孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/girl.c",
        ]),
        ([
                "id":          "cui biaotou",
                "name":        "崔镖头",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/fuzhou/npc/cui.c",
        ]),
        ([
                "id":          "chen apo",
                "name":        "陈阿婆",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/chen.c",
        ]),
        ([
                "id":          "su su",
                "name":        "素素",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/yanziwu/npc/susu.c",
        ]),
        ([
                "id":          "alamuhan",
                "name":        "阿拉木罕",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/xingxiu/npc/alamuhan.c",
        ]),
        ([
                "id":          "shudian laoban",
                "name":        "书店老板",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/xiangyang/npc/shudianboss.c",
        ]),
        ([
                "id":          "shaofan shifu",
                "name":        "烧饭师傅",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xiangyang/npc/shaofanshifu.c",
        ]),
        ([
                "id":          "zhong ling",
                "name":        "钟灵",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/zhongling.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "挑夫",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taishan/npc/tiao-fu.c",
        ]),
        ([
                "id":          "xiao hongniang",
                "name":        "小红娘",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/suzhou/npc/xiao-hongniang.c",
        ]),
        ([
                "id":          "ni gu",
                "name":        "尼姑",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/nigu2.c",
        ]),
        ([
                "id":          "ni gu",
                "name":        "尼姑",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/nigu1.c",
        ]),
        ([
                "id":          "ya huan",
                "name":        "丫环",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/lady3.c",
        ]),
        ([
                "id":          "kid",
                "name":        "小孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/kid.c",
        ]),
        ([
                "id":          "xiao fan",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-fan.c",
        ]),
        ([
                "id":          "xiang ke",
                "name":        "香客",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/quanzhen/npc/xiangke.c",
        ]),
        ([
                "id":          "poor man",
                "name":        "穷汉",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/poorman.c",
        ]),
        ([
                "id":          "cun min",
                "name":        "村民",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/cunmin.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xueshan/npc/xiaoer2.c",
        ]),
        ([
                "id":          "zhuoma",
                "name":        "卓玛",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/xuedao/npc/zhuoma.c",
        ]),
        ([
                "id":          "girl",
                "name":        "女孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/girl.c",
        ]),
        ([
                "id":          "jianghu haoke",
                "name":        "江湖豪客",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/haoke.c",
        ]),
        ([
                "id":          "xiao hai",
                "name":        "小孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-hai.c",
        ]),
        ([
                "id":          "shaofan seng",
                "name":        "烧饭僧",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/shaolin/npc/shaofan-seng.c",
        ]),
        ([
                "id":          "saodi seng",
                "name":        "扫地僧",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/shaolin/npc/saodi-seng.c",
        ]),
        ([
                "id":          "seller",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/quanzhen/npc/seller.c",
        ]),
        ([
                "id":          "girl",
                "name":        "女孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/girl.c",
        ]),
        ([
                "id":          "tong",
                "name":        "道童",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/quanzhen/npc/daotong.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "家丁",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/meizhuang/npc/jiading.c",
        ]),
        ([
                "id":          "zhangfang",
                "name":        "帐房先生",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/lingzhou/npc/zhangfang.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao huoji",
                "name":        "小伙计",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/lingzhou/npc/daodianhuoji.c",
        ]),
        ([
                "id":          "jianghu haoke",
                "name":        "江湖豪客",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/huashan/npc/haoke.c",
        ]),
        ([
                "id":          "yangzong",
                "name":        "央宗",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/xuedao/npc/yangzong.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/xiaoer2.c",
        ]),
        ([
                "id":          "lao qiao",
                "name":        "乔三槐",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/lao-qiao.c",
        ]),
        ([
                "id":          "da shou",
                "name":        "打手",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/shaolin/npc/da-shou.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/quanzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "kid",
                "name":        "小孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/heimuya/npc/kid.c",
        ]),
        ([
                "id":          "youke",
                "name":        "游客",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/you-ke.c",
        ]),
        ([
                "id":          "xiao ju",
                "name":        "小菊",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guiyun/npc/xiaoju.c",
        ]),
        ([
                "id":          "xiu cai",
                "name":        "落第秀才",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiucai.c",
        ]),
        ([
                "id":          "cun gu",
                "name":        "村姑",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/heimuya/npc/cungu.c",
        ]),
        ([
                "id":          "old woman",
                "name":        "老大娘",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/oldwoman.c",
        ]),
        ([
                "id":          "lao ban",
                "name":        "酒馆老板",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/guanwai/npc/laoban.c",
        ]),
        ([
                "id":          "seller",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaofan.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "zhong xiaoer",
                "name":        "钟小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/foshan/npc/zhongxiaoer.c",
        ]),
        ([
                "id":          "zhang chaotang",
                "name":        "张朝唐",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/foshan/npc/zhang.c",
        ]),
        ([
                "id":          "shou shangren",
                "name":        "瘦商人",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/foshan/npc/shou.c",
        ]),
        ([
                "id":          "pang shangren",
                "name":        "胖商人",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/foshan/npc/pang.c",
        ]),
        ([
                "id":          "feng qi",
                "name":        "凤七",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/foshan/npc/fengqi.c",
        ]),
        ([
                "id":          "nianqing shaofu",
                "name":        "年轻少妇",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/emei/npc/youngwoman.c",
        ]),
        ([
                "id":          "xiao fan",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/emei/npc/xiao-fan.c",
        ]),
        ([
                "id":          "girl",
                "name":        "维吾尔少女",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xingxiu/npc/shaonv.c",
        ]),
        ([
                "id":          "poor man",
                "name":        "穷汉",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/poorman.c",
        ]),
        ([
                "id":          "kid",
                "name":        "小孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/kid.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "家丁",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xiangyang/npc/jiading.c",
        ]),
        ([
                "id":          "boy",
                "name":        "男孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xiangyang/npc/boy.c",
        ]),
        ([
                "id":          "dibao",
                "name":        "地保",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/village/npc/dibao.c",
        ]),
        ([
                "id":          "saodi seng",
                "name":        "扫地僧",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/saodiseng.c",
        ]),
        ([
                "id":          "bi nu",
                "name":        "婢女",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/suzhou/npc/lady4.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "小沙弥",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-tong.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-er2.c",
        ]),
        ([
                "id":          "jingxiang ke",
                "name":        "进香客",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiang-ke.c",
        ]),
        ([
                "id":          "chen apo",
                "name":        "陈阿婆",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/quanzhou/npc/chen.c",
        ]),
        ([
                "id":          "boy",
                "name":        "男孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/quanzhou/npc/boy.c",
        ]),
        ([
                "id":          "jinxiang ke",
                "name":        "进香客",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xueshan/npc/xiang-ke.c",
        ]),
        ([
                "id":          "kid",
                "name":        "小孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xingxiu/npc/kid.c",
        ]),
        ([
                "id":          "jinxiang ke",
                "name":        "进香客",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/wudang/npc/guest.c",
        ]),
        ([
                "id":          "boy",
                "name":        "男孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/boy.c",
        ]),
        ([
                "id":          "cha boshi",
                "name":        "茶博士",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/henshan/npc/chaboshi.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "挑夫",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/tiao-fu.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "小沙弥",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/hangzhou/npc/shami.c",
        ]),
        ([
                "id":          "qianlong",
                "name":        "乾隆皇帝",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/qianlong.c",
        ]),
        ([
                "id":          "poor man",
                "name":        "穷汉",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/poorman.c",
        ]),
        ([
                "id":          "jinxiang ke",
                "name":        "进香客",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/guest.c",
        ]),
        ([
                "id":          "girl",
                "name":        "女孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/girl.c",
        ]),
        ([
                "id":          "girl",
                "name":        "采茶女",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/caichanu.c",
        ]),
        ([
                "id":          "boy",
                "name":        "男孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/boy.c",
        ]),
        ([
                "id":          "xiao lama",
                "name":        "小喇嘛",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xuedao/npc/x_lama.c",
        ]),
        ([
                "id":          "caiyao ren",
                "name":        "采药人",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xuedao/npc/caiyaoren.c",
        ]),
        ([
                "id":          "old woman",
                "name":        "老大娘",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/oldwoman.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taishan/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "qiao fu",
                "name":        "樵夫",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/huanghe/npc/qiaofu.c",
        ]),
        ([
                "id":          "liu furen",
                "name":        "刘夫人",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/henshan/npc/liufuren.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "pihuo shang",
                "name":        "皮货商",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/guanwai/npc/pihuoshang.c",
        ]),
        ([
                "id":          "xiao lama",
                "name":        "小喇嘛",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xueshan/npc/x_lama1.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "镖头",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/xiangyang/npc/biaotou.c",
        ]),
        ([
                "id":          "girl",
                "name":        "女孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/girl.c",
        ]),
        ([
                "id":          "bi nu",
                "name":        "婢女",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taohua/npc/binu.c",
        ]),
        ([
                "id":          "seller",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/seller.c",
        ]),
        ([
                "id":          "girl",
                "name":        "苏州女孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/lady1.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "小沙弥",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-nan.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-er.c",
        ]),
        ([
                "id":          "xiao shami",
                "name":        "小沙弥",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-ci.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "挑夫",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/tiao-fu.c",
        ]),
        ([
                "id":          "seng bing",
                "name":        "护林僧兵",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/shaolin/npc/seng-bing1.c",
        ]),
        ([
                "id":          "kid",
                "name":        "小孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/kid.c",
        ]),
        ([
                "id":          "jieyin shi",
                "name":        "接引使",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/mingjiao/npc/jieyinshi.c",
        ]),
        ([
                "id":          "woman",
                "name":        "维吾尔族妇女",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xingxiu/npc/woman.c",
        ]),
        ([
                "id":          "muyang ren",
                "name":        "牧羊人",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xingxiu/npc/herdsman.c",
        ]),
        ([
                "id":          "caiyao ren",
                "name":        "采药人",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xingxiu/npc/caiyaoren.c",
        ]),
        ([
                "id":          "wang yuyan",
                "name":        "王语嫣",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xiaoyao/npc/wangyuyan.c",
        ]),
        ([
                "id":          "lai fuer",
                "name":        "来福儿",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/fuer.c",
        ]),
        ([
                "id":          "seller",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/seller.c",
        ]),
        ([
                "id":          "kid",
                "name":        "小孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/village/npc/kid.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "书生",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taishan/npc/shu-sheng.c",
        ]),
        ([
                "id":          "girl",
                "name":        "苏州少女",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/lady2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/xiaoer1.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/xiaoer.c",
        ]),
        ([
                "id":          "chu shi",
                "name":        "厨师",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/meizhuang/npc/chushi.c",
        ]),
        ([
                "id":          "xiao shimei",
                "name":        "小师妹",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/huashan/npc/girldizi.c",
        ]),
        ([
                "id":          "youke",
                "name":        "游客",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/youke.c",
        ]),
        ([
                "id":          "yangcan nu",
                "name":        "养蚕女",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/yangcannu.c",
        ]),
        ([
                "id":          "xue laoban",
                "name":        "薛老板",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/xueboss.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao daogu",
                "name":        "小道姑",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/dali/npc/xiaodaogu.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "乌夷商贩",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/wshangfan.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "台夷商贩",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/tshangfan.c",
        ]),
        ([
                "id":          "tai jian",
                "name":        "太监",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/taijian.c",
        ]),
        ([
                "id":          "shi jiang",
                "name":        "石匠",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/shijiang.c",
        ]),
        ([
                "id":          "pihuo shang",
                "name":        "皮货商",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/pihuoshang.c",
        ]),
        ([
                "id":          "pei cong",
                "name":        "陪从",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/peicong.c",
        ]),
        ([
                "id":          "oldman",
                "name":        "摆夷老叟",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/oldman.c",
        ]),
        ([
                "id":          "nong fu",
                "name":        "农夫",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/dali/npc/nongfu2.c",
        ]),
        ([
                "id":          "nong fu",
                "name":        "台夷农妇",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/nongfu1.c",
        ]),
        ([
                "id":          "nong fu",
                "name":        "农夫",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/nongfu.c",
        ]),
        ([
                "id":          "muyang ren",
                "name":        "牧羊人",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/muyangren.c",
        ]),
        ([
                "id":          "muyang nv",
                "name":        "牧羊女",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/muyangnu.c",
        ]),
        ([
                "id":          "lao jisi",
                "name":        "乌夷老祭司",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/laojisi.c",
        ]),
        ([
                "id":          "kid",
                "name":        "摆夷小孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/kid.c",
        ]),
        ([
                "id":          "kanzhu ren",
                "name":        "砍竹人",
                "type":        "杀",
                "bonus":       57,
                "msg":        "",
                "object":      "/d/dali/npc/kanzhuren.c",
        ]),
        ([
                "id":          "guan jia",
                "name":        "管家",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/guanjia.c",
        ]),
        ([
                "id":          "girl",
                "name":        "南国姑娘",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/dali/npc/girl1.c",
        ]),
        ([
                "id":          "ge nu",
                "name":        "歌女",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/genu.c",
        ]),
        ([
                "id":          "fu nu",
                "name":        "台夷妇女",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/funu.c",
        ]),
        ([
                "id":          "fangsha nu",
                "name":        "纺纱女",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/dali/npc/fangshanu.c",
        ]),
        ([
                "id":          "cun fu",
                "name":        "村妇",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/cunfu.c",
        ]),
        ([
                "id":          "caisun ren",
                "name":        "采笋人",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/caisunren1.c",
        ]),
        ([
                "id":          "caisun ren",
                "name":        "采笋人",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/dali/npc/caisunren.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "台夷商贩",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/dali/npc/bshangfan.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "「平通镖局」镖头",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/biaotou.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/chengdu/npc/xiaoer2.c",
        ]),
        ([
                "id":          "yaodian huoji",
                "name":        "药店伙计",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/chengdu/npc/huoji.c",
        ]),
        ([
                "id":          "xiao guizi",
                "name":        "小桂子",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/xiaoguiz.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/xiaoer.c",
        ]),
        ([
                "id":          "tie jiang",
                "name":        "铁匠",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/smith.c",
        ]),
        ([
                "id":          "li apo",
                "name":        "李阿婆",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/liapo.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "药铺伙计",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/city/npc/huoji2.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "药铺伙计",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/huoji.c",
        ]),
        ([
                "id":          "hong niang",
                "name":        "红娘",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/city/npc/hongniang.c",
        ]),
        ([
                "id":          "biao tou",
                "name":        "镖头",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/city/npc/biaotou.c",
        ]),
        ([
                "id":          "aqing sao",
                "name":        "阿庆嫂",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/aqingsao.c",
        ]),
        ([
                "id":          "zi yi",
                "name":        "[35m紫衣[2;37;0m",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/ziyi.c",
        ]),
        ([
                "id":          "yahuan",
                "name":        "丫环",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/yahuan.c",
        ]),
        ([
                "id":          "xiaoer",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiaoer",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/changan/npc/xiaoer.c",
        ]),
        ([
                "id":          "waiter",
                "name":        "茶馆小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/teawaiter.c",
        ]),
        ([
                "id":          "ru hua",
                "name":        "如花",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/ruhua.c",
        ]),
        ([
                "id":          "qing yi",
                "name":        "[1;36m青衣[2;37;0m",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/qingyi.c",
        ]),
        ([
                "id":          "lv yi",
                "name":        "[1;32m绿衣[2;37;0m",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/luyi.c",
        ]),
        ([
                "id":          "lan yi",
                "name":        "[1;34m蓝衣[2;37;0m",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/lanyi.c",
        ]),
        ([
                "id":          "zhang lanxiang",
                "name":        "张兰香",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/lanxiang.c",
        ]),
        ([
                "id":          "ji nu",
                "name":        "妓女",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/jinu.c",
        ]),
        ([
                "id":          "huang yi",
                "name":        "[1;33m黄衣[2;37;0m",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/huangyi.c",
        ]),
        ([
                "id":          "hong yi",
                "name":        "[1;31m红衣[2;37;0m",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/hongyi.c",
        ]),
        ([
                "id":          "maihua guniang",
                "name":        "卖花姑娘",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/changan/npc/girl.c",
        ]),
        ([
                "id":          "fen yi",
                "name":        "[1;35m粉衣[2;37;0m",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/fenyi.c",
        ]),
        ([
                "id":          "shi jiugong",
                "name":        "时九公",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/doctor.c",
        ]),
        ([
                "id":          "bai yi",
                "name":        "[1;37m白衣[2;37;0m",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/changan/npc/baiyi.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/beijing/npc/xiaoer.c",
        ]),
        ([
                "id":          "flower girl",
                "name":        "卖花姑娘",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/beijing/npc/flowerg.c",
        ]),
        ([
                "id":          "zhang ma",
                "name":        "张妈",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/zhangma.c",
        ]),
        ([
                "id":          "ya huan",
                "name":        "丫环",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/yahuan.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/xiaoer.c",
        ]),
        ([
                "id":          "woman",
                "name":        "农家妇女",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/baituo/npc/woman.c",
        ]),
        ([
                "id":          "tiejiang",
                "name":        "铁匠",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/smith.c",
        ]),
        ([
                "id":          "qiao fu",
                "name":        "樵夫",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/qiaofu.c",
        ]),
        ([
                "id":          "man",
                "name":        "农民",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/baituo/npc/man.c",
        ]),
        ([
                "id":          "kid",
                "name":        "小孩",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/kid.c",
        ]),
        ([
                "id":          "jin hua",
                "name":        "金花",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/jinhua.c",
        ]),
        ([
                "id":          "cun gu",
                "name":        "村姑",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/baituo/npc/cungu.c",
        ]),
        ([
                "id":          "qing feng",
                "name":        "清风",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/wudang/qingfeng.c",
        ]),
        ([
                "id":          "ming yue",
                "name":        "明月",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/wudang/mingyue.c",
        ]),
        ([
                "id":          "daotong",
                "name":        "道童",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/wudang/daotong.c",
        ]),
        ([
                "id":          "xu tong",
                "name":        "虚通",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/xu-tong.c",
        ]),
        ([
                "id":          "qingyuan biqiu",
                "name":        "清缘比丘",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-yuan.c",
        ]),
        ([
                "id":          "qingxiao biqiu",
                "name":        "清晓比丘",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-xiao.c",
        ]),
        ([
                "id":          "qingwu biqiu",
                "name":        "清无比丘",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wu.c",
        ]),
        ([
                "id":          "qingwen biqiu",
                "name":        "清闻比丘",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wen.c",
        ]),
        ([
                "id":          "qingwei biqiu",
                "name":        "清为比丘",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-wei.c",
        ]),
        ([
                "id":          "qingshan biqiu",
                "name":        "清善比丘",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-shan.c",
        ]),
        ([
                "id":          "qingle biqiu",
                "name":        "清乐比丘",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-le.c",
        ]),
        ([
                "id":          "qingguan biqiu",
                "name":        "清观比丘",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-guan.c",
        ]),
        ([
                "id":          "qingfa biqiu",
                "name":        "清法比丘",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/qing-fa.c",
        ]),
        ([
                "id":          "zhao gouer",
                "name":        "赵狗儿",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/zhao-gouer.c",
        ]),
        ([
                "id":          "wenyin",
                "name":        "文音小师太",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/wenyin.c",
        ]),
        ([
                "id":          "wenqing",
                "name":        "文清小师太",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/wenqing.c",
        ]),
        ([
                "id":          "wenhui",
                "name":        "文晖小师太",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/wenhui.c",
        ]),
        ([
                "id":          "wenfang",
                "name":        "文方小师太",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/wenfang.c",
        ]),
        ([
                "id":          "daoming",
                "name":        "道明小师父",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/emei/daoming.c",
        ]),
        ([
                "id":          "hong niang",
                "name":        "红娘",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/adm/npc/hongniang.c",
        ]),
});
mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
