#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "wu jiang",
                "name":        "武将",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/xingxiu/npc/wujiang.c",
        ]),
        ([
                "id":          "li sao",
                "name":        "李嫂",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/lingjiu/npc/lisao.c",
        ]),
        ([
                "id":          "hao jie",
                "name":        "太湖豪杰",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guiyun/npc/haojie.c",
        ]),
        ([
                "id":          "zu touren",
                "name":        "族头人",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/dali/npc/zutouren.c",
        ]),
        ([
                "id":          "wu santong",
                "name":        "武三通",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wusantong.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "媒婆",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/suzhou/npc/meipo.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "武将",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/hanzhong/npc/wujiang.c",
        ]),
        ([
                "id":          "zhuang zheng",
                "name":        "庄铮",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/zhuangzheng.c",
        ]),
        ([
                "id":          "yue lingshan",
                "name":        "岳灵珊",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huashan/npc/yue-lingshan.c",
        ]),
        ([
                "id":          "liu jing",
                "name":        "刘菁",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/henshan/npc/liujing.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "白衣武士",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi1.c",
        ]),
        ([
                "id":          "shi sao",
                "name":        "石嫂",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/shisao.c",
        ]),
        ([
                "id":          "cheng qingshuang",
                "name":        "程青霜",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/cheng.c",
        ]),
        ([
                "id":          "xin yan",
                "name":        "心砚",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/xinyan.c",
        ]),
        ([
                "id":          "san hu",
                "name":        "忽伦三虎",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sanhu.c",
        ]),
        ([
                "id":          "wang jian",
                "name":        "王坚",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wang.c",
        ]),
        ([
                "id":          "zhou dian",
                "name":        "周颠",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/zhoudian.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "皇宫卫士",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/lingzhou/npc/gongweishi.c",
        ]),
        ([
                "id":          "zu qianqiu",
                "name":        "祖千秋",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huanghe/npc/zu.c",
        ]),
        ([
                "id":          "youfang daoren",
                "name":        "游方道人",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/npc/youfang.c",
        ]),
        ([
                "id":          "er hu",
                "name":        "忽伦二虎",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/erhu.c",
        ]),
        ([
                "id":          "da hu",
                "name":        "忽伦大虎",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/dahu.c",
        ]),
        ([
                "id":          "liu guoxuan",
                "name":        "刘国轩",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/taiwan/npc/liu.c",
        ]),
        ([
                "id":          "zhang zhong",
                "name":        "张中",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/zhangzhong.c",
        ]),
        ([
                "id":          "xin ran",
                "name":        "辛然",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/xinran.c",
        ]),
        ([
                "id":          "wen cangsong",
                "name":        "闻苍松",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/wensong.c",
        ]),
        ([
                "id":          "shuo bude",
                "name":        "说不得",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/shuobude.c",
        ]),
        ([
                "id":          "li tianyuan",
                "name":        "李天垣",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/litianyuan.c",
        ]),
        ([
                "id":          "leng qian",
                "name":        "冷谦",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/lengqian.c",
        ]),
        ([
                "id":          "yun zhonghe",
                "name":        "云中鹤",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/lingzhou/npc/yun.c",
        ]),
        ([
                "id":          "luo bing",
                "name":        "骆冰",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/luo.c",
        ]),
        ([
                "id":          "jiang sigen",
                "name":        "蒋四根",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/jiang.c",
        ]),
        ([
                "id":          "sun popo",
                "name":        "孙婆婆",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/gumu/npc/sun.c",
        ]),
        ([
                "id":          "ding jian",
                "name":        "丁坚",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/meizhuang/ding.c",
        ]),
        ([
                "id":          "wu xiuwen",
                "name":        "武修文",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wuxiuwen.c",
        ]),
        ([
                "id":          "yao hou",
                "name":        "乐厚",
                "type":        "杀",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/songshan/yao.c",
        ]),
        ([
                "id":          "zhu ziliu",
                "name":        "朱子柳",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/zhuziliu.c",
        ]),
        ([
                "id":          "pian jiang",
                "name":        "偏将",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/xiangyang/npc/pian.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "红衣武士",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi2.c",
        ]),
        ([
                "id":          "yin wushou",
                "name":        "殷无寿",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/yinwushou.c",
        ]),
        ([
                "id":          "yin wufu",
                "name":        "殷无福",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/yinwufu.c",
        ]),
        ([
                "id":          "yan yuan",
                "name":        "颜垣",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/yanyuan.c",
        ]),
        ([
                "id":          "lu guanying",
                "name":        "陆冠英",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/guiyun/npc/xiaolu.c",
        ]),
        ([
                "id":          "wanyan kang",
                "name":        "完颜康",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/d/guiyun/npc/wanyankang.c",
        ]),
        ([
                "id":          "lu guanying",
                "name":        "陆冠英",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/guiyun/npc/xiaolu.c",
        ]),
        ([
                "id":          "si hu",
                "name":        "忽伦四虎",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sihu.c",
        ]),
        ([
                "id":          "huta seng",
                "name":        "护塔僧",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/hutaseng1.c",
        ]),
        ([
                "id":          "shou mu",
                "name":        "守墓家奴",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/taohua/npc/shoumu.c",
        ]),
        ([
                "id":          "tang yang",
                "name":        "唐洋",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/tangyang.c",
        ]),
        ([
                "id":          "peng yingyu",
                "name":        "彭莹玉",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/pengyingyu.c",
        ]),
        ([
                "id":          "hu qingniu",
                "name":        "胡青牛",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/mingjiao/npc/hu.c",
        ]),
        ([
                "id":          "nu erhai",
                "name":        "努儿海",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/lingzhou/npc/nuerhai.c",
        ]),
        ([
                "id":          "yin yewang",
                "name":        "殷野王",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/yinyewang.c",
        ]),
        ([
                "id":          "yin wulu",
                "name":        "殷无禄",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/yinwulu.c",
        ]),
        ([
                "id":          "shen zhifan",
                "name":        "申志凡",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/shen.c",
        ]),
        ([
                "id":          "qi zhicheng",
                "name":        "祁志诚",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/qi.c",
        ]),
        ([
                "id":          "pi qingxuan",
                "name":        "皮清玄",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/pi.c",
        ]),
        ([
                "id":          "li zhichang",
                "name":        "李志常",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/li.c",
        ]),
        ([
                "id":          "fang zhiqi",
                "name":        "房志起",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/fang.c",
        ]),
        ([
                "id":          "cui zhifang",
                "name":        "崔志方",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/cui.c",
        ]),
        ([
                "id":          "cheng yaojia",
                "name":        "程瑶迦",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/cheng.c",
        ]),
        ([
                "id":          "ping si",
                "name":        "平四",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/hu/pingsi.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "武将",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/dali/npc/jiang.c",
        ]),
        ([
                "id":          "huo xiansheng",
                "name":        "霍先生",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/dali/npc/huo.c",
        ]),
        ([
                "id":          "da tusi",
                "name":        "大土司",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/dali/npc/datusi.c",
        ]),
        ([
                "id":          "shi cong",
                "name":        "侍从",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/chengdu/npc/shicong.c",
        ]),
        ([
                "id":          "qin bing",
                "name":        "亲兵",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/chengdu/npc/qinbing.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "武将",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/city/npc/wujiang.c",
        ]),
        ([
                "id":          "yulin jun",
                "name":        "御林军",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/d/changan/npc/yulinjun.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "武将",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/wujiang.c",
        ]),
        ([
                "id":          "murong hao",
                "name":        "慕容豪",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/changan/npc/murong-hao.c",
        ]),
        ([
                "id":          "jing xuan",
                "name":        "净玄",
                "type":        "杀",
                "bonus":       79,
                "msg":        "",
                "object":      "/d/changan/npc/jingxuan.c",
        ]),
        ([
                "id":          "jing ming",
                "name":        "净明",
                "type":        "杀",
                "bonus":       79,
                "msg":        "",
                "object":      "/d/changan/npc/jingming.c",
        ]),
        ([
                "id":          "da shou",
                "name":        "打手",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/dashou.c",
        ]),
        ([
                "id":          "chen laoban",
                "name":        "陈老板",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/chen-laoban.c",
        ]),
        ([
                "id":          "bu tou",
                "name":        "捕头",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/butou.c",
        ]),
        ([
                "id":          "zhao qixian",
                "name":        "赵齐贤",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/beijing/npc/zhaoqi.c",
        ]),
        ([
                "id":          "zhang kangnian",
                "name":        "张康年",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/beijing/npc/zhangkang.c",
        ]),
        ([
                "id":          "xu tianchuan",
                "name":        "徐天川",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/beijing/npc/xutianchuan.c",
        ]),
        ([
                "id":          "san furen",
                "name":        "庄夫人",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/beijing/npc/furen.c",
        ]),
        ([
                "id":          "xuan zhen",
                "name":        "玄贞道长",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/yunlong/xuanzhen.c",
        ]),
        ([
                "id":          "xue muhua",
                "name":        "薛慕华",
                "type":        "杀",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/xuemuh.c",
        ]),
        ([
                "id":          "gou du",
                "name":        "苟读",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/goudu.c",
        ]),
        ([
                "id":          "chengzhi luohan",
                "name":        "澄志",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-zhi2.c",
        ]),
        ([
                "id":          "chengzhi luohan",
                "name":        "澄知",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-zhi.c",
        ]),
        ([
                "id":          "chengyu luohan",
                "name":        "澄欲",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-yu.c",
        ]),
        ([
                "id":          "chengyi luohan",
                "name":        "澄意",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-yi.c",
        ]),
        ([
                "id":          "chengxing luohan",
                "name":        "澄行",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-xing.c",
        ]),
        ([
                "id":          "chengxin luohan",
                "name":        "澄信",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-xin2.c",
        ]),
        ([
                "id":          "chengxin luohan",
                "name":        "澄心",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-xin.c",
        ]),
        ([
                "id":          "chengsi luohan",
                "name":        "澄思",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-si.c",
        ]),
        ([
                "id":          "chengshi luohan",
                "name":        "澄识",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-shi.c",
        ]),
        ([
                "id":          "chengshang luohan",
                "name":        "澄尚",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-shang.c",
        ]),
        ([
                "id":          "chengming luohan",
                "name":        "澄明",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-ming.c",
        ]),
        ([
                "id":          "chengmie luohan",
                "name":        "澄灭",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-mie.c",
        ]),
        ([
                "id":          "chengling luohan",
                "name":        "澄灵",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-ling.c",
        ]),
        ([
                "id":          "chengjing luohan",
                "name":        "澄净",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-jing.c",
        ]),
        ([
                "id":          "chengjian luohan",
                "name":        "澄坚",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-jian.c",
        ]),
        ([
                "id":          "chengji luohan",
                "name":        "澄寂",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-ji.c",
        ]),
        ([
                "id":          "chenghe luohan",
                "name":        "澄和",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-he.c",
        ]),
        ([
                "id":          "chengguan luohan",
                "name":        "澄观",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/cheng-guan.c",
        ]),
        ([
                "id":          "zhang zhiguang",
                "name":        "张志光",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/zhang.c",
        ]),
        ([
                "id":          "wang zhitan",
                "name":        "王志坦",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/wangzhitan.c",
        ]),
        ([
                "id":          "kuai huosan",
                "name":        "快活三",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/kuai-huosan.c",
        ]),
        ([
                "id":          "jiang shangyou",
                "name":        "江上游",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/jiang-sy.c",
        ]),
        ([
                "id":          "jingzhen shitai",
                "name":        "静真师太",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/emei/zhen.c",
        ]),
        ([
                "id":          "jingzhao shitai",
                "name":        "静照师太",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/emei/zhao.c",
        ]),
        ([
                "id":          "jingxin shitai",
                "name":        "静心师太",
                "type":        "杀",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/emei/xin.c",
        ]),
        ([
                "id":          "jingxian shitai",
                "name":        "静闲师太",
                "type":        "杀",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/emei/xian.c",
        ]),
        ([
                "id":          "zhao lingzhu",
                "name":        "赵灵珠",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/emei/ling.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "媒婆",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/adm/npc/meipo.c",
        ]),
});
mapping query_quesths()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
