// Created by Smallfish For HUAXIA@2004    2004/04/24

#include <ansi.h>

mapping cloth_obj = ([
        "/d/yanziwu/obj/cloth":1,                     //暂时无处获取
        "/d/yanziwu/npc/obj/pink_cloth":28,           //阿朱
        "/d/yanziwu/npc/obj/green_cloth":28,          //阿碧
        "/d/yanziwu/npc/obj/cloth":1,                 //暂时无处获取
        "/d/xueshan/obj/y-jiasha":8,                  //很多
        "/d/xueshan/obj/r-jiasha":28,                 //鸠摩智
        "/d/xueshan/obj/p-jiasha":28,                 //金轮法王
        "/d/xueshan/obj/lamajiasha":12,               //祭祀喇嘛、值日喇嘛、达尔巴
        "/d/xueshan/obj/c-jiasha":20,                 //老年僧人、贡唐仓国师、灵智上人
        "/d/xueshan/obj/b-jiasha":12,                 //守寺僧兵、葛伦布、本参、本观、本相、本因
        "/d/xuedao/obj/dachang":23,                   //血刀门山洞
        "/d/xingxiu/obj/yellow-cloth":24,             //阿紫、游坦之
        "/d/xingxiu/obj/junfu":1,                     //暂时无处获取
        "/d/xingxiu/obj/changpao":1,                  //暂时无处获取
        "/d/xiaoyao/npc/obj/cloth":20,                //逍遥蒙面人、王语嫣
        "/d/xiakedao/obj/cloth":1,                    //暂时无处获取
        "/d/xiakedao/npc/obj/ycloth":1,               //暂时无处获取
        "/d/xiakedao/npc/obj/bcloth":1,               //暂时无处获取
        "/d/wudang/obj/wuxingfu":15,                  //五行弟子
        "/d/wudang/obj/whiterobe":12,                 //武当比较多
        "/d/wudang/obj/greyrobe":10,                  //相当多
        "/d/wudang/obj/greenrobe":15,                 //小翠、谷虚道长、知客道长、李莫愁
        "/d/wudang/obj/bluecloth":10,                 //比较多
        "/d/wudang/obj/baguafu":15,                   //八卦弟子
        "/d/wanjiegu/npc/obj/zi-dress":1,             //暂时无处获取
        "/d/wanjiegu/npc/obj/yan-dress":1,            //暂时无处获取
        "/d/wanjiegu/npc/obj/xiu-cloth":1,            //暂时无处获取
        "/d/wanjiegu/npc/obj/xian-cloth":1,           //暂时无处获取
        "/d/wanjiegu/npc/obj/sha-dress":1,            //暂时无处获取
        "/d/wanjiegu/npc/obj/red-dress":1,            //暂时无处获取
        "/d/wanjiegu/npc/obj/qing-cloth":28,          //段延庆
        "/d/wanjiegu/npc/obj/qi-dress":28,            //东方不败
        "/d/wanjiegu/npc/obj/pink-dress":28,          //木婉清
        "/d/wanjiegu/npc/obj/pink-cloth":26,          //甘宝宝
        "/d/wanjiegu/npc/obj/moon-dress":26,          //钟灵
        "/d/wanjiegu/npc/obj/mini-dress":26,          //进喜儿
        "/d/wanjiegu/npc/obj/marry-dress":1,          //暂时无处获取
        "/d/wanjiegu/npc/obj/liu-dress":1,            //暂时无处获取
        "/d/wanjiegu/npc/obj/gui-dress":1,            //暂时无处获取
        "/d/wanjiegu/npc/obj/fu-cloth":1,             //暂时无处获取
        "/d/wanjiegu/npc/obj/feature":1,              //暂时无处获取
        "/d/wanjiegu/npc/obj/dress":1,                //暂时无处获取
        "/d/wanjiegu/npc/obj/color-dress":1,          //暂时无处获取
        "/d/wanjiegu/npc/obj/cloth":22,               //来福儿、黄眉大师、钟万仇
        "/d/wanjiegu/npc/obj/blake-cloth":24,         //万劫谷山路江湖豪客
        "/d/village/npc/obj/cloth":4,                 //很多
        "/d/tulong/yitian/npc/obj/jiaofu":1,          //暂时无处获取
        "/d/tulong/tulong/npc/obj/jiaofu":22,         //明教三使
        "/d/taohua/obj/cubupao":1,                    //暂时无处获取
        "/d/taohua/obj/bupao":28,                     //黄药师
        "/d/taohua/obj/baiyi":26,                     //程英
        "/d/taohua/obj/baipao":22,                    //桃花岛仆人
        "/d/taohua/obj/baichou":1,                    //暂时无处获取
        "/d/suzhou/npc/obj/yunxiu":4,                 //媒婆
        "/d/suzhou/npc/obj/yayifu":15,                //苏州衙役
        "/d/suzhou/npc/obj/longpao":0,                //不收
        "/d/shaolin/obj/xuan-cloth":12,               //少林比较多
        "/d/shaolin/obj/xu-cloth":1,                  //暂时无处获取
        "/d/shaolin/obj/test":1,                      //暂时无处获取
        "/d/shaolin/obj/qing-cloth":12,               //少林比较多
        "/d/shaolin/obj/hui-cloth":12,                //少林比较多
        "/d/shaolin/obj/dao-cloth":12,                //少林比较多
        "/d/shaolin/obj/cloth":10,                    //少林相当多
        "/d/shaolin/obj/cheng-cloth":8,               //少林很多
        "/d/shaolin/obj/beixin":12,                   //道相禅师索取
        "/d/quanzhou/pig/obj/rover":1,                //暂时无处获取
        "/d/quanzhou/obj/pink_cloth":4,               //陈阿婆购买
        "/d/quanzhou/obj/cloth":1,                    //暂时无处获取
        "/d/quanzhou/npc/obj/cloth":12,               //泉州男孩女孩
        "/d/quanzhen/npc/obj/junfu":15,               //武功镇官兵
        "/d/quanzhen/npc/obj/jinduan":26,             //侯员外
        "/d/quanzhen/npc/obj/greyrobe":1,             //暂时无处获取
        "/d/quanzhen/npc/obj/greenrobe":26,           //王重阳、周伯通
        "/d/quanzhen/npc/obj/grayrobe":4,             //很多
        "/d/quanzhen/npc/obj/goupi":15,               //富家侧门
        "/d/quanzhen/npc/obj/cloth":4,                //很多
        "/d/mingjiao/obj/beixin":1,                   //暂时无处获取
        "/d/mingjiao/obj/baipao":8,                   //明教很多
        "/d/meizhuang/npc/obj/qingyi":12,             //梅庄家丁
        "/d/meizhuang/npc/obj/heiyi":1,               //暂时无处获取
        "/d/lingjiu/obj/qingyi":12,                   //灵鹫相当多
        "/d/lingjiu/obj/doupeng":12,                  //灵鹫相当多
        "/d/lingjiu/obj/changpao":28,                 //虚竹
        "/d/huanghe/npc/obj/shuikao":1,               //暂时无处获取
        "/d/huanghe/npc/obj/changpao":28,             //梁子翁
        "/d/henshan/npc/obj/luo_cloth":28,            //刘正风
        "/d/henshan/npc/obj/blackcloth":28,           //曲洋
        "/d/heimuya/obj/cloth":1,                     //暂时无处获取
        "/d/heimuya/npc/obj/zichoush":24,             //紫衫侍者
        "/d/heimuya/npc/obj/zaohong":28,              //杨莲亭
        "/d/heimuya/npc/obj/hongchouxiaoshan":1,      //暂时无处获取
        "/d/heimuya/npc/obj/cloth":4,                 //很多
        "/d/hangzhou/npc/obj/sahua-qun":26,           //情儿
        "/d/hangzhou/npc/obj/goupi":1,                //暂时无处获取
        "/d/hangzhou/npc/obj/cloth":8,                //杭州比较多
        "/d/hangzhou/npc/obj/baibu-qingshan":26,      //月下书生
        "/d/hangzhou/honghua/obj/huangshan":28,       //霍青桐
        "/d/gumu/npc/obj/baipao":1,                   //暂时无处获取
        "/d/guiyun/npc/obj/red_cloth":24,             //小菊、小兰
        "/d/guiyun/npc/obj/green_cloth":28,           //南希仁
        "/d/guanwai/npc/obj/piqiu":6,                 //皮货商购买
        "/d/fuzhou/obj/pink_cloth":4,                 //陈阿婆购买
        "/d/fuzhou/obj/cloth":1,                      //暂时无处获取
        "/d/fuzhou/npc/obj/cloth":8,                  //福州男孩女孩
        "/d/fuzhou/npc/obj/bluecloth":1,              //暂时无处获取
        "/d/foshan/npc/obj/magcloth":24,              //佛山胖商人、瘦商人
        "/d/foshan/npc/obj/goupi":12,                 //佛山狼狗（四只）
        "/d/emei/obj/ycloth":24,                      //袁紫衣、周芷若
        "/d/emei/npc/obj/cloth":28,                   //穷汉
        "/d/dali/npc/obj/xiaoao":24,                  //台夷猎手、渔夫
        "/d/dali/npc/obj/whitecloth1":22,             //南国姑娘、宫女、木婉清
        "/d/dali/npc/obj/whitecloth":20,              //摆夷女子、宫女、南国姑娘
        "/d/dali/npc/obj/wdahui":18,                  //乌夷老祭司、猎人、农夫、乌夷商贩
        "/d/dali/npc/obj/wchangqun":18,               //养花女、牧羊女、牧羊人、少女
        "/d/dali/npc/obj/tongqun":16,                 //采笋人、台夷妇女、台夷姑娘、祭司、台夷农妇、族长
        "/d/dali/npc/obj/tduanqun":20,                //村妇、台夷商贩
        "/d/dali/npc/obj/qun":4,                      //薛老板购买
        "/d/dali/npc/obj/maotan":20,                  //采笋人、砍竹人、农夫
        "/d/dali/npc/obj/kenao":4,                    //歌女、薛老板购买
        "/d/dali/npc/obj/junfu":8,                    //很多
        "/d/dali/npc/obj/jjunfu":24,                  //锦衣卫士（两个）
        "/d/dali/npc/obj/hupi":28,                    //傣族首领
        "/d/dali/npc/obj/guazi":4,                    //薛老板购买
        "/d/dali/npc/obj/doupeng":1,                  //暂时无处获取
        "/d/dali/npc/obj/cynrobe":22,                 //小道姑（两个）、刀白凤
        "/d/dali/npc/obj/bduanqun":16,                //台夷商贩、采桑女、纺纱女、老祭司、养蚕女
        "/d/city/obj/yayifu":1,                       //暂时无处获取
        "/d/city/obj/pink_cloth":4,                   //胡掌柜购买、韦春芳、采花子
        "/d/city/obj/junfu":8,                        //很多
        "/d/city/obj/goupi":1,                        //暂时无处获取
        "/d/city/obj/cloth":4,                        //很多
        "/d/city/obj/beixin":4,                       //胡掌柜购买
        "/d/city/npc/obj/yayifu":8,                   //扬州衙门、灵州衙门
        "/d/city/npc/obj/qunzi":1,                    //暂时无处获取
        "/d/city/npc/obj/pink_cloth":24,              //崔莺莺、程玉环
        "/d/city/npc/obj/junfu":10,                   //很多
        "/d/city/npc/obj/jinsijia":12,                //杨永福购买
        "/d/city/npc/obj/goupi":12,                   //比较多
        "/d/city/npc/obj/cloth":4,                    //很多
        "/d/city/npc/obj/beixin":6,                   //杨永福购买
        "/d/city/npc/cloth/zi-dress":4,               //曾柔购买
        "/d/city/npc/cloth/yan-dress":4,              //曾柔购买
        "/d/city/npc/cloth/xiu-cloth":4,              //曾柔购买
        "/d/city/npc/cloth/xian-cloth":4,             //曾柔购买
        "/d/city/npc/cloth/sha-dress":4,              //曾柔购买
        "/d/city/npc/cloth/red-dress":4,              //曾柔购买
        "/d/city/npc/cloth/qi-dress":4,               //曾柔购买
        "/d/city/npc/cloth/pink-dress":4,             //曾柔购买
        "/d/city/npc/cloth/moon-dress":4,             //曾柔购买
        "/d/city/npc/cloth/mini-dress":4,             //曾柔购买
        "/d/city/npc/cloth/marry-dress":4,            //曾柔购买
        "/d/city/npc/cloth/liu-dress":4,              //曾柔购买
        "/d/city/npc/cloth/gui-dress":4,              //曾柔购买
        "/d/city/npc/cloth/fu-cloth":4,               //曾柔购买
        "/d/city/npc/cloth/feature":4,                //曾柔购买
        "/d/city/npc/cloth/dress":1,                  //暂时无处获取
        "/d/city/npc/cloth/color-dress":4,            //曾柔购买
        "/d/city/npc/cloth/cloth":4,                  //曾柔购买
        "/d/changan/npc/obj/yayifu":15,               //长安衙门
        "/d/changan/npc/obj/skirt":12,                //相当多
        "/d/changan/npc/obj/sengyi":24,               //宝象寺知客僧(两个)
        "/d/changan/npc/obj/sengpao":22,              //慧通禅师、静明、静玄
        "/d/changan/npc/obj/linen":4,                 //伙计、店小二
        "/d/changan/npc/obj/jinzhuang":4,             //很多
        "/d/changan/npc/obj/cloth":4,                 //很多
        "/d/changan/npc/obj/choupao":10,              //相当多
        "/d/changan/npc/obj/changpao":12,             //管家、说书老人、刘老实、香客、戏子
        "/d/changan/npc/obj/bingfu":8,                //很多
        "/d/changan/npc/obj/beixin":4,                //刘老实购买
        "/d/beijing/npc/obj/nvcloth":10,              //相当多
        "/d/beijing/npc/obj/jinvcloth":24,            //妓女（两个）
        "/d/beijing/npc/obj/jiasha":8,                //很多
        "/d/beijing/npc/obj/hupi":26,                 //归钟、喜来福
        "/d/beijing/npc/obj/guanfu6":8,               //很多
        "/d/beijing/npc/obj/guanfu5":20,              //城门督察（四个）、冯锡范
        "/d/beijing/npc/obj/guanfu4":15,              //东厂官兵、西厂官兵
        "/d/beijing/npc/obj/guanfu3":24,              //骁骑营侍卫(两个）
        "/d/beijing/npc/obj/guanfu2":22,              //多隆、张康年、赵齐贤
        "/d/beijing/npc/obj/guanfu1":15,              //御前侍卫（八个）
        "/d/beijing/npc/obj/goldcloth2":28,           //康亲王
        "/d/beijing/npc/obj/goldcloth1":22,           //鳌拜、多隆、郑克爽
        "/d/beijing/npc/obj/diaoqiu":24,              //鳌拜、韦小宝
        "/d/beijing/npc/obj/cloth6":24,               //齐元凯、麦鲸、过三拳、元广波
        "/d/beijing/npc/obj/cloth5":28,               //归辛树
        "/d/beijing/npc/obj/cloth4":20,               //独臂神尼、归二娘、富家弟子、殷素素
        "/d/beijing/npc/obj/cloth3":1,                //暂时无处获取
        "/d/beijing/npc/obj/cloth2":22,               //酸秀才（三个）
        "/d/beijing/npc/obj/cloth1":8,                //毒郎中、柳大洪、书生、张翠山
        "/d/beijing/npc/obj/cloth":4,                 //很多
        "/d/baituo/obj/shepi":22,                     //白驼蟒蛇
        "/d/baituo/obj/qingpao":28,                   //小青
        "/d/baituo/obj/baipao":15,                    //管家、白衣少女、田伯光、欧阳克、舞蛇人
        "/d/baituo/npc/obj/shepi":1,                  //暂时无处获取
        "/d/baituo/npc/obj/qingpao":1,                //暂时无处获取
        "/d/baituo/npc/obj/baipao":1,                 //暂时无处获取
        "/clone/misc/red_cloth":1,                    //公共文件一律廉价
        "/clone/misc/pink_cloth":1,                   //公共文件一律廉价
        "/clone/misc/color_cloth":1,                  //公共文件一律廉价
        "/clone/misc/cloth":1,                        //公共文件一律廉价
        "/clone/misc/black_cloth":1,                  //公共文件一律廉价
        "/clone/misc/baipao":1,                       //公共文件一律廉价
        "/clone/cloth/yunshang":1,                    //公共文件一律廉价
        "/clone/cloth/y-jiasha":1,                    //公共文件一律廉价
        "/clone/cloth/wcloth":1,                      //公共文件一律廉价
        "/clone/cloth/seng-cloth":1,                  //公共文件一律廉价
        "/clone/cloth/qingyi":1,                      //公共文件一律廉价
        "/clone/cloth/ni-cloth":1,                    //公共文件一律廉价
        "/clone/cloth/male8-cloth":1,                 //公共文件一律廉价
        "/clone/cloth/male7-cloth":1,                 //公共文件一律廉价
        "/clone/cloth/male6-cloth":1,                 //公共文件一律廉价
        "/clone/cloth/male5-cloth":1,                 //公共文件一律廉价
        "/clone/cloth/male4-cloth":1,                 //公共文件一律廉价
        "/clone/cloth/male3-cloth":1,                 //公共文件一律廉价
        "/clone/cloth/male2-cloth":1,                 //公共文件一律廉价
        "/clone/cloth/male1-cloth":1,                 //公共文件一律廉价
        "/clone/cloth/junfu":1,                       //公共文件一律廉价
        "/clone/cloth/jinduan":1,                     //公共文件一律廉价
        "/clone/cloth/female8-cloth":1,               //公共文件一律廉价
        "/clone/cloth/female7-cloth":1,               //公共文件一律廉价
        "/clone/cloth/female6-cloth":1,               //公共文件一律廉价
        "/clone/cloth/female5-cloth":1,               //公共文件一律廉价
        "/clone/cloth/female4-cloth":1,               //公共文件一律廉价
        "/clone/cloth/female3-cloth":1,               //公共文件一律廉价
        "/clone/cloth/female2-cloth":1,               //公共文件一律廉价
        "/clone/cloth/female1-cloth":1,               //公共文件一律廉价
        "/clone/cloth/daogu-cloth":1,                 //公共文件一律廉价
        "/clone/cloth/dao-cloth":1,                   //公共文件一律廉价
        "/clone/cloth/cuttonp":1,                     //公共文件一律廉价
        "/clone/cloth/cloth":1,                       //公共文件一律廉价
        "/clone/cloth/changpao":1,                    //公共文件一律廉价
        "/clone/cloth/c-jiasha":1,                    //公共文件一律廉价
        "/clone/cloth/bupao":1,                       //公共文件一律廉价
        "/clone/cloth/baipao":1,                      //公共文件一律廉价
        "/clone/book/zhanyi":1,                       //公共文件一律廉价
        "/kungfu/class/dali/obj/magcloth":28,         //高升泰
]);

int check_value(string filename)
{
        if (undefinedp(cloth_obj[filename])) return 0;
        return cloth_obj[filename];
}
