// Create by Rcwiz for Hero May 2003
//

mapping fam_info = ([

      "武当派"    :     ([ "shen_type"     :    1,                               // 门派神类型1为正神，-1为负神
                           "master_id"     :    "zhang sanfeng",                 // 门派最高Master ID
                           "master_name"   :    "张三丰",                        // 门派最高Master name
                           "master_rank"   :    "张真人",                        // 门派最高Master rank
                           "master_file"   :    CLASS_D("wudang") + "/zhang",    // 门派最高Master所属文件
                           "master_room"   :    "/d/wudang/xiaoyuan",            // 门派最高Master起始房间
                           "fir_room_fi"   :    "/d/wudang/toutiangate",         // 挑畔者初始聚集地
                           "fir_room_nm"   :    "头天门",
                           "tar_room_fi"   :    "/d/wudang/xiaoyuan",            // 挑畔者夺取目标地点
                           "tar_room_nm"   :    "后山小院",
                           "guard_room_fi" :    "/d/wudang/wulaofeng",           // 门派NPC守卫地点
                           "guard_room_nm" :    "五老峰",
                           "npc_list"      :    ({ 
                                                   "yu lianzhou",                // 门派中的其他NPC参与接受挑畔
                                                   "yin litin",                  // 这些NPC均会在开始时移动到
                                                   "yu daiyan",                  // master_room 并与master组队
                                                   "song qingshu", 
                                                   "zhang songxi",
                                                   "song yuanqiao",
                                                   "mo shenggu",
                                                }),
                           "route_list"    :    ({                               // 记录挑畔者攻打该门派所经过的路由 
                                                   "north",                      // 每次random_move()都读取该路由表
                                                   "north",                      // 按照这个顺序一直走到终点
                                                   "northdown", 
                                                   "northdown", 
                                                   "northdown", 
                                                   "northdown", 
                                                   "northdown", 
                                                   "northup", 
                                                   "northdown", 
                                                   "northdown", 
                                                   "west", 
                                                   "west", // 武当广场
                                                   "south",
                                                   "south",
                                                   "south",
                                                   "south",
                                                   "south",
                                                 }),
                          "skill"          :     "太极剑法和太极神功",
                          "family"         :     "武当派",
                          "spe_cmds"       :     "open door",
                        ]),

      "逍遥派"    :     ([ "shen_type"     :    1,
                           "master_id"     :    "su xinghe",
                           "master_name"   :    "苏星河",
                           "master_rank"   :    "掌门人",
                           "master_file"   :    CLASS_D("xiaoyao") + "/suxingh",
                           "master_room"   :    "/d/xiaoyao/qingcaop",
                           "fir_room_fi"   :    "/d/xiaoyao/shulin3",
                           "fir_room_nm"   :    "逍遥派树林",
                           "tar_room_fi"   :    "/d/xiaoyao/shishi",
                           "tar_room_nm"   :    "石室",
                           "guard_room_fi" :    "/d/xiaoyao/qingcaop",
                           "guard_room_nm" :    "青草坪",
                           "npc_list"      :    ({ 
                                                   "xue muhua",
                                                   "wu lingjun",
                                                   "shi qinglu", 
                                                   "kang guangling",
                                                   "feng asan",
                                                   "fan bailing",
                                                }),
                           "route_list"    :    ({
                                                   "east",
                                                   "south",
                                                   "west",
                                                   "west",
                                                   "enter",
                                                   "down",
                                                 }),
                          "skill"          :     "天山六阳掌和北冥神功",
                          "family"         :     "逍遥派",
                        ]),

      "峨嵋派"    :     ([ "shen_type"     :    1,
                           "master_id"     :    "miejue shitai",
                           "master_name"   :    "灭绝师太",
                           "master_rank"   :    "掌门人",
                           "master_file"   :    CLASS_D("emei") + "/miejue",
                           "master_room"   :    "/d/emei/hcahoudian",
                           "fir_room_fi"   :    "/d/emei/shierpan1",
                           "fir_room_nm"   :    "十二盘",
                           "tar_room_fi"   :    "/d/emei/hcahoudian",
                           "tar_room_nm"   :    "华藏庵后殿",
                           "guard_room_fi" :    "/d/emei/leidongping",
                           "guard_room_nm" :    "雷洞坪",
                           "npc_list"      :    ({
                                                   "bei jinyi",
                                                   "jingdao shitai",
                                                   "jinghe shitai",
                                                   "zhou zhiruo", 
                                                   "jingzhen shitai",
                                                   "jingzhao shitai",
                                                   "jingxuan shitai",
                                                   "jingxu shitai",
                                                   "jingxin shitai",
                                                   "jingxian shitai",
                                                   "jingkong shitai",
                                                   "jingjia shitai",
                                                   "jinghui shitai",
                                                   "fengling shitai",
                                                   "jingfeng shitai",
                                                   "jingxuan shitai",
                                                   "jingxuan shitai",
                                                }),
                           "route_list"    :    ({
                                                   "southwest",
                                                   "westup",
                                                   "southwest",
                                                   "westup",
                                                   "westup",
                                                   "westup",
                                                   "westup",
                                                   "westup",
                                                   "southup",
                                                   "southup",
                                                   "southup",
                                                   "southwest",
                                                   "southup",
                                                   "southeast",
                                                   "westup",
                                                   "southup", // 金顶
                                                   "southeast",
                                                   "enter",
                                                   "south",
                                                   "south",
                                                   "south",
                                                 }),
                          "skill"          :     "回风拂柳剑和峨嵋九阳神功",
                          "family"         :     "峨嵋派",
                        ]),

      "灵鹫宫"    :     ([ "shen_type"     :    1,
                           "master_id"     :    "xuzhu zhi",
                           "master_name"   :    "虚竹子",
                           "master_rank"   :    "掌门人",
                           "master_file"   :    CLASS_D("lingjiu") + "/xuzhu",
                           "master_room"   :    "/d/lingjiu/dating",
                           "fir_room_fi"   :    "/d/lingjiu/shanjiao",
                           "fir_room_nm"   :    "缥缈峰山脚",
                           "tar_room_fi"   :    "/d/lingjiu/dating",
                           "tar_room_nm"   :    "独尊厅",
                           "guard_room_fi" :    "/d/lingjiu/xianchou",
                           "guard_room_nm" :    "仙愁门",
                           "npc_list"      :    ({
                                                   "cheng qingshuang",
                                                   "duanmu yuan",
                                                   "fu mingyi",
                                                   "ju jian", 
                                                   "lan jian",
                                                   "li furen",
                                                   "mei jian",
                                                   "sang tugong",
                                                   "shi sao",
                                                   "zhu jian",
                                                   "zhuo bufan",
                                                   "zuo zimu",
                                                }),
                           "route_list"    :    ({
                                                   "westup",
                                                   "westup",
                                                   "northup",
                                                   "eastup",
                                                   "north",
                                                   "north",
                                                   "north",
                                                 }),
                          "skill"          :     "八荒六合唯我独尊功和天山六阳掌",
                          "family"         :     "灵鹫宫",
                          "spe_cmds"       :     "zou tiesuo",
                        ]),

      "星宿派"    :     ([ "shen_type"     :    -1,
                           "master_id"     :    "ding chunqiu",
                           "master_name"   :    "丁春秋",
                           "master_rank"   :    "老仙",
                           "master_file"   :    CLASS_D("xingxiu") + "/ding",
                           "master_room"   :    "/d/xingxiu/riyuedong",
                           "fir_room_fi"   :    "/d/xingxiu/shanjiao",
                           "fir_room_nm"   :    "天山脚下",
                           "tar_room_fi"   :    "/d/xingxiu/riyuedong",
                           "tar_room_nm"   :    "日月洞",
                           "guard_room_fi" :    "/d/xingxiu/xxh1",
                           "guard_room_nm" :    "星宿海",
                           "npc_list"      :    ({
                                                   "chuchen zi",
                                                   "tianlang zi",
                                                   "zhaixing zi",
                                                }),
                           "route_list"    :    ({
                                                   "westup",
                                                   "north",
                                                   "northdown",
                                                   "north",
                                                   "north",
                                                 }),
                          "skill"          :     "抽髓掌和毒技",
                          "family"         :     "星宿派",
                        ]),
      "全真派"    :     ([ "shen_type"     :    1,
                           "master_id"     :    "wang chongyang",
                           "master_name"   :    "王重阳",
                           "master_rank"   :    "掌门人",
                           "master_file"   :    CLASS_D("quanzhen") + "/wang",
                           "master_room"   :    "/d/quanzhen/shandong",
                           "fir_room_fi"   :    "/d/gumu/riyueyan",
                           "fir_room_nm"   :    "日月岩",
                           "tar_room_fi"   :    "/d/quanzhen/shandong",
                           "tar_room_nm"   :    "后山山洞",
                           "guard_room_fi" :    "/d/gumu/daxiaochang",
                           "guard_room_nm" :    "大校场",
                           "npc_list"      :    ({
                                                   "hao datong",
                                                   "liu chuxuan",
                                                   "ma yu",
                                                   "qiu chuji",
                                                   "tan chuduan",
                                                   "wang chuyi",
                                                   "yin zhiping",
                                                   "zhao zhijing",
                                                   "zhou botong",
                                                }),
                           "route_list"    :    ({
                                                   "northup",
                                                   "northup",
                                                   "north",
                                                   "west",
                                                   "northwest",
                                                   "north",
                                                   "northup",
                                                   "northup",
                                                   "northup",
                                                   "northup",
                                                   "northup",
                                                   "southeast",
                                                   "eastup",
                                                   "southup",
                                                   "east", // jiaobei
                                                   "eastup", // 有门
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east",
                                                   "east", // 后山 - /d/quanzhen/houshan
                                                   "northeast",
                                                   "northeast",
                                                   "east",
                                                   "enter",
                                                 }),
                          "skill"          :     "全真剑法和先天功",
                          "family"         :     "全真教",
                          "spe_cmds"       :     "open door",
                        ]),
]);