inherit SKILL;
mapping *quest = ({
      (["short":                "大理北门",
       "place" :              "/d/dali/northgate",]),  
      (["short":                "扬州密林",
       "place" :              "/d/city/jiaowai5",]),  
     (["short":                "峨嵋草棚",
       "place" :              "/d/emei/caopeng",]),
     (["short":                "扬州西门",
       "place" :              "/d/city/ximen",]),
     (["short":                "雪山土路",
       "place" :              "/d/xueshan/tulu2",]),
     (["short":                "苏州留园",
       "place" :              "/d/suzhou/liuyuan",]),
     (["short":                "苏州寒山寺",
       "place" :              "/d/suzhou/hanshansi",]),
     (["short":                "杭州飞来峰",
       "place" :              "/d/hangzhou/feilaifeng",]),
     (["short":                "杭州净慈寺",
       "place" :              "/d/hangzhou/jingcisi",]),
     (["short":                "杭州翠微亭",
       "place" :              "/d/hangzhou/cuiweiting",]),
     (["short":                "杭州聚景园",
       "place" :              "/d/hangzhou/jujingyuan",]),
     (["short":                "苗疆易溪部",
       "place" :              "/d/dali/yixibu",]),  
      (["short":                "扬州中央广场",
       "place" :              "/d/city/guangchang",]),  
      (["short":                "杭州沿湖大道",
       "place" :              "/d/hangzhou/dadao1",]), 
      (["short":                "杭州断桥",
       "place" :              "/d/hangzhou/duanqiao",]), 
      (["short":                "杭州灵隐寺",
       "place" :              "/d/hangzhou/lingyinsi",]), 
/*
      (["short":                "星宿海伊犁",
       "place" :              "/d/xingxiu/beijiang",]), 
*/
      (["short":                "武当三天门",
       "place" :              "/d/wudang/santiangate",]), 
      (["short":                "峨嵋十二盘",
       "place" :              "/d/emei/shierpan3",]), 
      (["short":                "峨嵋千佛庵",
       "place" :              "/d/emei/qianfoan",]), 
      (["short":                "峨嵋九十九道拐",
       "place" :              "/d/emei/jsjdg1",]), 
      (["short":                "明教厚土旗门",
       "place" :              "/d/mingjiao/htqmen",]), 
      (["short":                "明教烈火旗后门",
       "place" :              "/d/mingjiao/lhqhoumen",]), 
      (["short":                "福州东门",
       "place" :              "/d/fuzhou/dongmen",]), 
      (["short":                "福州北大街",
       "place" :              "/d/fuzhou/beidajie",]), 
/*
      (["short":                "星宿海沙漠",
       "place" :              "/d/xingxiu/shamo2",]),
*/
      (["short":                "少林寺石阶",
       "place" :              "/d/shaolin/shijie4",]),
      (["short":                "襄阳石阶",
       "place" :              "/d/xiangyang/walle1",]),
      (["short":                "华山猢狲愁",
       "place" :              "/d/huashan/husun",]),
      (["short":                "华山玉女峰",
       "place" :              "/d/huashan/yunu",]),
      (["short":                "慕容小径",
       "place" :              "/d/mr/xiaojing1-2",]),
      (["short":                "慕容柳树林",
       "place" :              "/d/mr/liulin",]),
      (["short":                "大理大和街",
       "place" :              "/d/dali/dahejiewest",]),
      (["short":                "苏州城北门",
       "place" :              "/d/suzhou/beimen",]),
      (["short":                "苏州城玄妙观",
       "place" :              "/d/suzhou/xuanmiao",]),
      (["short":                "少林寺山门殿",
       "place" :              "/d/shaolin/smdian",]),
      (["short":                "少林寺走廊",
       "place" :              "/d/shaolin/zoulang7",]),
      (["short":                "武当山路",
       "place" :              "/d/wudang/shanlu3",]),
      (["short":                "少林寺般若堂九部",
       "place" :              "/d/shaolin/banruo9",]),
      (["short":                "雪山山脚",
       "place" :              "/d/xueshan/shanjiao",]),
      (["short":                "峨嵋九老洞",
       "place" :              "/d/emei/jiulaodong",]),
       (["short":                "峨嵋古德林",
       "place" :              "/d/emei/gudelin1",]),
       (["short":                "函古关",
       "place" :              "/d/quanzhen/hanguguan",]),
       (["short":                "终南山口",
       "place" :              "/d/quanzhen/zhongnan",]),
       (["short":                "闽江",
       "place" :              "/d/fuzhou/fzroad8",]),
       (["short":                "汉水南岸",
       "place" :              "/d/shaolin/hanshui1",]),
       (["short":                "中条山密林",
       "place" :              "/d/huashan/jzroad5",]),
       (["short":                "天山脚下",
       "place" :              "/d/xingxiu/shanjiao",]),
       (["short":                "华山脚下",
       "place" :              "/d/huashan/path1",]),
       (["short":                "平定州",
       "place" :              "/d/heimuya/pingdingzhou",]),
       (["short":                "乱石坡",
       "place" :              "/d/heimuya/road1",]),      
       ([      "short":                "华山村南村口",
                "place":                "/d/village/sexit",
        ]),([      "short":                "闽赣古道",
                "place":                "/d/fuzhou/fzroad7",
        ]),([     "short":                "玉皇顶",
                 "place":               "/d/taishan/yuhuang",
         ]),([      "short":                "六盘山",
                "place":                "/d/xingxiu/xxroad3",
        ]),([      "short":                "天山山路",
                "place":                "/d/xingxiu/tianroad1",
        ]),([      "short":                "嘉峪关",
                "place":                "/d/xingxiu/jiayuguan",
        ]),([      "short":                "西单北大街",
                "place":                "/d/city2/xidan1",
        ]),([      "short":                "武道场",
                "place":                "/d/city/wudao4",
        ]),([      "short":                "王府井大街",
                "place":                "/d/city2/wangfu2",
        ]),([      "short":                "全真教碑",
                "place":                "/d/quanzhen/jiaobei",
        ]),([      "short":                "老妪岩",
                "place":                "/d/gumu/juyan",
        ]),([      "short":                "老龙头",
                "place":                "/d/guanwai/laolongtou",
        ]),([      "short":                "嘉兴城",
                "place":                "/d/quanzhou/jiaxing",
        ]),([      "short":                "扬州西门",
                "place":                "/d/city/ximen",
        ]),([      "short":                "仙霞岭",
                "place":                "/d/fuzhou/fzroad1",
        ]),([      "short":                "宁远",
                "place":                "/d/taishan/yitian",
        ]),([      "short":                "小土屋",
                "place":                "/d/guanwai/tuwu",
        ]),([      "short":                "下关城",
                "place":                "/d/dali/xiaguan",
        ]),([      "short":                "李子箐石林",
                 "place":                "/d/dali/shilin1",
        ]),([      "short":                "大叠水瀑布",
                 "place":                "/d/dali/dadieshui",
        ]),([      "short":                "罗伽甸",
                 "place":                "/d/dali/luojiadian",
        ]),([      "short":                "阳宗镇",

                 "place":                "/d/dali/yangzong",
        ]),([      "short":                "太室阙",
                 "place":                "/d/songshan/taishique",
        ]),([      "short":                "少林石阶",
                 "place":                "/d/shaolin/shijie7",
        ]),([      "short":                "铁梁峡",
                 "place":                "/d/songshan/tieliang",
        ]),([      "short":                "峻极禅院山门",
                 "place":                "/d/songshan/junjigate",
        ]),([      "short":                "神禾原",
                 "place":                "/d/gumu/shenheyuan",
        ]),([      "short":                "终南山大校场",
                 "place":                "/d/gumu/daxiaochang",
        ]),([      "short":                "金锁关",
                 "place":                "/d/huashan/jinsuo",
        ]),([      "short":                "平心石",
                 "place":                "/d/huashan/pingxinshi",
        ]),([      "short":                "千尺幢",
                 "place":                "/d/huashan/qianchi",
        ]),([      "short":                "山洪瀑布",
                 "place":                "/d/huashan/shanhongpb",
        ]),([      "short":                "清音阁",
                 "place":                "/d/emei/qingyinge",
        ]),([      "short":                "十二盘",
                 "place":                "/d/emei/shierpan1",
        ]),([      "short":                "九老洞口",
                 "place":                "/d/emei/jldongkou",
        ]),([      "short":                "九十九道拐",
                 "place":                "/d/emei/jsjdg2",
        ]),([      "short":                "千佛庵",
                 "place":                "/d/emei/qianfoan",
        ]),([      "short":                "终南山空地",
                 "place":                "/d/gumu/kongdi",
        ]),([      "short":                "终南山主峰",
                 "place":                "/d/gumu/zhufeng",
        ]),([      "short":                "悬天崖",
                 "place":                "/d/mingjiao/shanlu3",
        ]), ([      "short":                "烈火旗大门",
                 "place":                "/d/mingjiao/lhqmen",
        ]),([      "short":                "雪山寺山门",
                 "place":                "/d/xueshan/shanmen",
        ]),([      "short":                "洪水旗大门",
                 "place":                "/d/mingjiao/hsqmen",
        ]),([      "short":                "洪水旗大门",
                 "place":                "/d/mingjiao/hsqmen",
        ]),([      "short":                "北大街",
                 "place":                "/d/mingjiao/hsqmen",
        ]),([      "short":                "青石大道",
                 "place":                "/d/wudang/wdroad1",
        ]),([      "short":                "关洛道",
                 "place":                "/d/city4/road1",
        ]),([      "short":                "大驿道",
                 "place":                "/d/taishan/yidao",
        ]),([      "short":                "官道",
                 "place":                "/d/quanzhen/guandao2",
        ]),([      "short":                "东街",
                 "place":                "/d/quanzhen/dongjie",
        ]),([      "short":                "富家大门",
                 "place":                "/d/quanzhen/fu-damen",
        ]),([      "short":                "山路",
                 "place":                "/d/quanzhen/shanlu1",
        ]),([      "short":                "小村庄",
                 "place":                "/d/quanzhen/xiaocun",
        ]),([      "short":                "星宿海",
                 "place":                "/d/xingxiu/xxh2",
        ]),([      "short":                "天山脚下",
                 "place":                "/d/xingxiu/shanjiao",
        ]),([      "short":                "丝绸之路",
                 "place":                "/d/xingxiu/silk2",

        ]),([      "short":                "长安城西门",
                 "place":                "/d/city4/westgate",
        ]),([      "short":                "长安城东门",
                 "place":                "/d/city4/eastgate",
        ]),([      "short":                "城东门",
                 "place":                "/d/city4/eastgate",
        ]),([      "short":                "上天梯",
                 "place":                "/d/huashan/shangtianti",
        ]),([      "short":                "树林",
                 "place":                "/d/xiaoyao/shulin3",
        ]),([      "short":                "南大街",
                 "place":                "/d/xiaoyao/shulin3",
        ]),      

   

      });

mapping query_quest()
{
  return quest[random(sizeof(quest))];
}
