//天干编号：甲、乙、丙、丁、戊、己、庚、辛、壬、癸
//地支编号：子、丑、寅、卯、辰、巳、午、未、申、酉、戌、亥
//宅基地块细目表

mapping *house_base = ({
([
    "name"  : "皇亭街甲号",
    "place" : "无锡",
    "type"  : "user",
    "file"  : "wuxi_01",
    "value" : 5000,
]),
([
    "name"  : "皇亭街乙号",
    "place" : "无锡",
    "type"  : "user",
    "file"  : "wuxi_02",
    "value" : 5000,
]),
([
    "name"  : "皇亭街丙号",
    "place" : "无锡",
    "type"  : "user",
    "file"  : "wuxi_03",
    "value" : 4800,
]),
([
    "name"  : "皇亭街丁号",
    "place" : "无锡",
    "type"  : "user",
    "file"  : "wuxi_04",
    "value" : 4800,
]),
([
    "name"  : "皇亭街戊号",
    "place" : "无锡",
    "type"  : "user",
    "file"  : "wuxi_05",
    "value" : 5000,
]),
([
    "name"  : "皇亭街己号",
    "place" : "无锡",
    "type"  : "user",
    "file"  : "wuxi_06",
    "value" : 5000,
]),
([
    "name"  : "皇亭街庚号",
    "place" : "无锡",
    "type"  : "user",
    "file"  : "wuxi_07",
    "value" : 4800,
]),
([
    "name"  : "皇亭街辛号",
    "place" : "无锡",
    "type"  : "user",
    "file"  : "wuxi_08",
    "value" : 4800,
]),
([
    "name"  : "南山路甲号",
    "place" : "临安",
    "type"  : "user",
    "file"  : "linan_01",
    "value" : 4000,
]),
([
    "name"  : "南山路乙号",
    "place" : "临安",
    "type"  : "user",
    "file"  : "linan_02",
    "value" : 4000,
]),
([
    "name"  : "南山路丙号",
    "place" : "临安",
    "type"  : "user",
    "file"  : "linan_03",
    "value" : 4000,
]),
([
    "name"  : "南山路丁号",
    "place" : "临安",
    "type"  : "user",
    "file"  : "linan_04",
    "value" : 4000,
]),
([
    "name"  : "南山路戊号",
    "place" : "临安",
    "type"  : "user",
    "file"  : "linan_05",
    "value" : 4000,
]),
([
    "name"  : "南山路己号",
    "place" : "临安",
    "type"  : "user",
    "file"  : "linan_06",
    "value" : 4000,
]),
([
    "name"  : "南山路庚号",
    "place" : "临安",
    "type"  : "user",
    "file"  : "linan_07",
    "value" : 4000,
]),
([
    "name"  : "南山路辛号",
    "place" : "临安",
    "type"  : "user",
    "file"  : "linan_08",
    "value" : 4000,
]),
([
    "name"  : "永定街甲号",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_01",
    "value" : 4500,
]),
([
    "name"  : "永定街乙号",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_02",
    "value" : 4500,
]),
([
    "name"  : "永定街丙号",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_03",
    "value" : 4500,
]),
([
    "name"  : "永定街丁号",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_04",
    "value" : 4500,
]),
([
    "name"  : "永定街戊号",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_05",
    "value" : 4500,
]),
([
    "name"  : "永定街己号",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_06",
    "value" : 4500,
]),
([
    "name"  : "永定街庚号",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_07",
    "value" : 4500,
]),
([
    "name"  : "永定街辛号",
    "place" : "北京",
    "type"  : "user",
    "file"  : "beijings_08",
    "value" : 4500,
]),
([
    "name"  : "侯监集甲号",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_01",
    "value" : 3000,
]),
([
    "name"  : "侯监集乙号",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_02",
    "value" : 3000,
]),
([
    "name"  : "侯监集丙号",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_03",
    "value" : 3000,
]),
([
    "name"  : "侯监集丁号",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_04",
    "value" : 2800,
]),
([
    "name"  : "侯监集戊号",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_05",
    "value" : 2800,
]),
([
    "name"  : "侯监集己号",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_06",
    "value" : 2800,
]),
([
    "name"  : "侯监集庚号",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_07",
    "value" : 2800,
]),
([
    "name"  : "侯监集辛号",
    "place" : "汝州",
    "type"  : "user",
    "file"  : "houjianji_08",
    "value" : 2800,
]),
([
    "name"  : "镇南街甲号",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_01",
    "value" : 3800,
]),
([
    "name"  : "镇南街乙号",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_02",
    "value" : 3800,
]),
([
    "name"  : "镇南街丙号",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_03",
    "value" : 3600,
]),
([
    "name"  : "镇南街丁号",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_04",
    "value" : 3600,
]),
([
    "name"  : "镇南街戊号",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_05",
    "value" : 3800,
]),
([
    "name"  : "镇南街己号",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_06",
    "value" : 3800,
]),
([
    "name"  : "镇南街庚号",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_07",
    "value" : 3600,
]),
([
    "name"  : "镇南街辛号",
    "place" : "大理",
    "type"  : "user",
    "file"  : "dali_08",
    "value" : 3600,
]),
([
    "name"  : "惠山峰腰",
    "place" : "无锡",
    "type"  : "bang",
    "file"  : "bang_01",
    "value" : 12000,
]),
([
    "name"  : "莲蓉桥堍",
    "place" : "无锡",
    "type"  : "bang",
    "file"  : "bang_02",
    "value" : 13000,
]),
([
    "name"  : "清名桥畔",
    "place" : "无锡",
    "type"  : "bang",
    "file"  : "bang_03",
    "value" : 15000,
]),
([
    "name"  : "孤山脚下",
    "place" : "临安",
    "type"  : "bang",
    "file"  : "bang_04",
    "value" : 10000,
]),
([
    "name"  : "清平路西",
    "place" : "福州",
    "type"  : "bang",
    "file"  : "bang_05",
    "value" : 10000,
]),
([
    "name"  : "龙泉山麓",
    "place" : "昆明",
    "type"  : "bang",
    "file"  : "bang_06",
    "value" : 9000,
]),
([
    "name"  : "西山脚下",
    "place" : "大理",
    "type"  : "bang",
    "file"  : "bang_07",
    "value" : 8000,
]),
([
    "name"  : "得胜山侧",
    "place" : "扬州",
    "type"  : "bang",
    "file"  : "bang_08",
    "value" : 9000,
]),
([
    "name"  : "沧州镇东",
    "place" : "沧州",
    "type"  : "bang",
    "file"  : "bang_09",
    "value" : 8000,
]),
([
    "name"  : "侯监林内",
    "place" : "汝州",
    "type"  : "bang",
    "file"  : "bang_10",
    "value" : 6000,
]),
([
    "name"  : "川中驿道",
    "place" : "四川",
    "type"  : "bang",
    "file"  : "bang_11",
    "value" : 7000,
]),
([
    "name"  : "北市口外",
    "place" : "北京",
    "type"  : "bang",
    "file"  : "bang_12",
    "value" : 12000,
]),
([
    "name"  : "安定门外",
    "place" : "北京",
    "type"  : "bang",
    "file"  : "bang_13",
    "value" : 10000,
]),
([
    "name"  : "燕山村西",
    "place" : "关外",
    "type"  : "bang",
    "file"  : "bang_14",
    "value" : 8000,
]),
([
    "name"  : "华山村东",
    "place" : "华山",
    "type"  : "bang",
    "file"  : "bang_15",
    "value" : 7000,
]),
([
    "name"  : "终南山脚",
    "place" : "全真",
    "type"  : "bang",
    "file"  : "bang_16",
    "value" : 6000,
]),
//---------帮会驻地二期版块-----TOP
([
    "name"  : "太平柱石",
    "place" : "武当",
    "type"  : "bang",
    "file"  : "bang_17",
    "value" : 36000,
]),
([
    "name"  : "双旗揽雪",
    "place" : "白驼",
    "type"  : "bang",
    "file"  : "bang_18",
    "value" : 24000,
]),
([
    "name"  : "南湖柳岸",
    "place" : "嘉兴",
    "type"  : "bang",
    "file"  : "bang_19",
    "value" : 36000,
]),
([
    "name"  : "山海雄风",
    "place" : "关外",
    "type"  : "bang",
    "file"  : "bang_20",
    "value" : 26000,
]),
([
    "name"  : "大沽海景",
    "place" : "北京",
    "type"  : "bang",
    "file"  : "bang_21",
    "value" : 34000,
]),
([
    "name"  : "阳关叠韵",
    "place" : "兰州",
    "type"  : "bang",
    "file"  : "bang_22",
    "value" : 28000,
]),
([
    "name"  : "青城寻幽",
    "place" : "青城",
    "type"  : "bang",
    "file"  : "bang_23",
    "value" : 28000,
]),
([
    "name"  : "禅钟唱晚",
    "place" : "峨嵋",
    "type"  : "bang",
    "file"  : "bang_24",
    "value" : 30000,
]),
([
    "name"  : "玉山西风",
    "place" : "昆仑",
    "type"  : "bang",
    "file"  : "bang_25",
    "value" : 28000,
]),
([
    "name"  : "东岳山景",
    "place" : "泰山",
    "type"  : "bang",
    "file"  : "bang_26",
    "value" : 32000,
]),
([
    "name"  : "少室问鼎",
    "place" : "少林",
    "type"  : "bang",
    "file"  : "bang_27",
    "value" : 34000,
]),
([
    "name"  : "桃花胜境",
    "place" : "峨嵋",
    "type"  : "bang",
    "file"  : "bang_28",
    "value" : 28000,
]),
//---------帮会驻地二期版块-----END
([
    "name"  : "小蓬莱",
    "place" : "散仙庄",
    "type"  : "xian",
    "file"  : "xian_01",
    "value" : 0,
]),
([
    "name"  : "小瀛洲",
    "place" : "散仙庄",
    "type"  : "xian",
    "file"  : "xian_02",
    "value" : 0,
]),
([
    "name"  : "小方壶",
    "place" : "散仙庄",
    "type"  : "xian",
    "file"  : "xian_03",
    "value" : 0,
]),
([
    "name"  : "小员峤",
    "place" : "散仙庄",
    "type"  : "xian",
    "file"  : "xian_04",
    "value" : 0,
]),
([
    "name"  : "小岱舆",
    "place" : "散仙庄",
    "type"  : "xian",
    "file"  : "xian_05",
    "value" : 0,
]),
});
