#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "liang ziwen",
                "name":        "梁子翁",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/huanghe/npc/liang.c",
        ]),
        ([
                "id":          "shang sanniang",
                "name":        "桑三娘",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/heimuya/npc/shang.c",
        ]),
        ([
                "id":          "jiao wenqi",
                "name":        "焦文期",
                "type":        "杀",
                "bonus":       58,
                "msg":        "",
                "object":      "/d/guanwai/npc/jiaowenqi.c",
        ]),
        ([
                "id":          "zhang seng",
                "name":        "杖僧",
                "type":        "杀",
                "bonus":       86,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/18jingang-4zhang.c",
        ]),
        ([
                "id":          "sha tongtian",
                "name":        "沙通天",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/huanghe/npc/sha.c",
        ]),
        ([
                "id":          "chu yuan",
                "name":        "褚圆",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/hangzhou/npc/chuyuan.c",
        ]),
        ([
                "id":          "xiao yuanshan",
                "name":        "萧远山",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiaoyuanshan.c",
        ]),
        ([
                "id":          "tongbai xiong",
                "name":        "童百熊",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/heimuya/npc/tongbw.c",
        ]),
        ([
                "id":          "jia bu",
                "name":        "贾布",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/heimuya/npc/jiabu.c",
        ]),
        ([
                "id":          "tian boguang",
                "name":        "田伯光",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/henshan/npc/tian.c",
        ]),
        ([
                "id":          "wang cheng",
                "name":        "王诚",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/heimuya/npc/wangcheng.c",
        ]),
        ([
                "id":          "long jun",
                "name":        "龙骏",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/npc/longjun.c",
        ]),
        ([
                "id":          "hu qingyu",
                "name":        "胡庆余",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/hangzhou/npc/huqingyu.c",
        ]),
        ([
                "id":          "shangguan yun",
                "name":        "上官云",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/heimuya/npc/shanggy.c",
        ]),
        ([
                "id":          "teng yilei",
                "name":        "滕一雷",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/guanwai/npc/tengyilei.c",
        ]),
        ([
                "id":          "bo seng",
                "name":        "钹僧",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/18jingang-4bo.c",
        ]),
        ([
                "id":          "peng lianhu",
                "name":        "彭连虎",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/huanghe/npc/peng.c",
        ]),
        ([
                "id":          "deng banian",
                "name":        "邓八年",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/songshan/npc/deng.c",
        ]),
        ([
                "id":          "ren yingying",
                "name":        "任盈盈",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/huashan/npc/ren-yingying.c",
        ]),
        ([
                "id":          "ouyang ke",
                "name":        "欧阳克",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/kungfu/class/ouyang/ouyangke.c",
        ]),
        ([
                "id":          "cheng lingsu",
                "name":        "程灵素",
                "type":        "杀",
                "bonus":       97,
                "msg":        "",
                "object":      "/kungfu/class/hu/cheng.c",
        ]),
        ([
                "id":          "xiao qun",
                "name":        "萧群",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/tongling2.c",
        ]),
        ([
                "id":          "zhang heng",
                "name":        "张衡",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/tongling1.c",
        ]),
        ([
                "id":          "li",
                "name":        "李管家",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/d/baituo/npc/li.c",
        ]),
        ([
                "id":          "samu huofo",
                "name":        "萨木活佛",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/samu.c",
        ]),
        ([
                "id":          "lingzhi shangren",
                "name":        "灵智上人",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/lingzhi.c",
        ]),
        ([
                "id":          "jiamu huofo",
                "name":        "嘉木活佛",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/jiamu.c",
        ]),
        ([
                "id":          "daerba huofo",
                "name":        "达尔巴",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/daerba.c",
        ]),
        ([
                "id":          "bao xiang",
                "name":        "宝象",
                "type":        "杀",
                "bonus":       72,
                "msg":        "",
                "object":      "/kungfu/class/xuedao/baoxiang.c",
        ]),
        ([
                "id":          "zhaixing zi",
                "name":        "摘星子",
                "type":        "杀",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/xingxiu/zhaixing.c",
        ]),
        ([
                "id":          "shihou zi",
                "name":        "狮吼子",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/xingxiu/shihou.c",
        ]),
        ([
                "id":          "chuchen zi",
                "name":        "出尘子",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/xingxiu/chuchen.c",
        ]),
        ([
                "id":          "song qingshu",
                "name":        "宋青书",
                "type":        "杀",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/wudang/xiaosong.c",
        ]),
        ([
                "id":          "huang rong",
                "name":        "黄蓉",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/taohua/rong.c",
        ]),
        ([
                "id":          "yin jin",
                "name":        "殷锦",
                "type":        "杀",
                "bonus":       92,
                "msg":        "",
                "object":      "/kungfu/class/shenlong/yin.c",
        ]),
        ([
                "id":          "lu gaoxuan",
                "name":        "陆高轩",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/kungfu/class/shenlong/lu.c",
        ]),
        ([
                "id":          "li mochou",
                "name":        "李莫愁",
                "type":        "杀",
                "bonus":       97,
                "msg":        "",
                "object":      "/kungfu/class/gumu/li.c",
        ]),
        ([
                "id":          "zuo quan",
                "name":        "左全",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/zuo-qu.c",
        ]),
        ([
                "id":          "ma juwei",
                "name":        "马俱为",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/ma-jw.c",
        ]),
        ([
                "id":          "li futou",
                "name":        "李斧头",
                "type":        "杀",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/li-futou.c",
        ]),
        ([
                "id":          "he bujing",
                "name":        "何不净",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/he-bj.c",
        ]),
});
mapping query_questdg()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
