#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "ye tu",
                "name":        "野兔",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xueshan/npc/yetu.c",
        ]),
        ([
                "id":          "mu jiang",
                "name":        "木匠",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xiangyang/npc/mujiang.c",
        ]),
        ([
                "id":          "jin xier",
                "name":        "进喜儿",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/xier.c",
        ]),
        ([
                "id":          "lao shu",
                "name":        "老鼠",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/ad-laoshu.c",
        ]),
        ([
                "id":          "tong",
                "name":        "小道童",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/quanzhen/npc/daotong1.c",
        ]),
        ([
                "id":          "lamb",
                "name":        "[1;33m野黄羊[2;37;0m",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/clone/quarry/yang3.c",
        ]),
        ([
                "id":          "fortune teller",
                "name":        "李铁嘴",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/huashan/npc/teller.c",
        ]),
        ([
                "id":          "heersu",
                "name":        "赫尔苏",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/guanwai/npc/heersu.c",
        ]),
        ([
                "id":          "meihua cilu",
                "name":        "[33m梅花雌鹿[2;37;0m",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/clone/quarry/lu3.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "家丁",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/foshan/npc/jiading.c",
        ]),
        ([
                "id":          "bee",
                "name":        "蜜蜂",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/foshan/npc/bee.c",
        ]),
        ([
                "id":          "seller",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/emei/npc/xiao-fan.c",
        ]),
        ([
                "id":          "little monkey",
                "name":        "小猴",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/emei/npc/little_monkey.c",
        ]),
        ([
                "id":          "big frog",
                "name":        "[32m大青蛙[2;37;0m",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/emei/npc/frog.c",
        ]),
        ([
                "id":          "bianfu",
                "name":        "蝙蝠",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/clone/quarry/fu.c",
        ]),
        ([
                "id":          "xiao lama",
                "name":        "小喇嘛",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xueshan/npc/x_lama.c",
        ]),
        ([
                "id":          "dipi",
                "name":        "地痞",
                "type":        "杀",
                "bonus":       48,
                "msg":        "",
                "object":      "/d/village/npc/dipi.c",
        ]),
        ([
                "id":          "laonian sengren",
                "name":        "老年僧人",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/tianlongsi/npc/laoniansengren.c",
        ]),
        ([
                "id":          "punk",
                "name":        "小流氓",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hanzhong/npc/punk.c",
        ]),
        ([
                "id":          "lin pingzhi",
                "name":        "林平之",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/huashan/npc/lin-pingzhi.c",
        ]),
        ([
                "id":          "huoji",
                "name":        "伙计",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/huanghe/npc/huoji.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/henshan/npc/xiaoer2.c",
        ]),
        ([
                "id":          "lao zhe",
                "name":        "老者",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/heimuya/npc/laozhe.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "书生",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/shu-sheng.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "书生",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/shu-sheng.c",
        ]),
        ([
                "id":          "punk",
                "name":        "小流氓",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/village/npc/punk.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "药铺伙计",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/suzhou/npc/huoji.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "家丁",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/henshan/npc/jiading.c",
        ]),
        ([
                "id":          "jiao tu",
                "name":        "日月神教教徒",
                "type":        "杀",
                "bonus":       48,
                "msg":        "",
                "object":      "/d/heimuya/npc/jiaotu.c",
        ]),
        ([
                "id":          "yufeng",
                "name":        "[1;37m玉蜂[2;37;0m",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/gumu/npc/yufeng.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer3.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "yahuan",
                "name":        "丫环",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/yanziwu/npc/yahuan.c",
        ]),
        ([
                "id":          "nan pu",
                "name":        "男仆",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/yanziwu/npc/nanpu.c",
        ]),
        ([
                "id":          "sha chong",
                "name":        "沙虫",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xingxiu/npc/shachong.c",
        ]),
        ([
                "id":          "shudian laoban",
                "name":        "书店老板",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/xiangyang/npc/shudianboss.c",
        ]),
        ([
                "id":          "shaofan shifu",
                "name":        "烧饭师傅",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xiangyang/npc/shaofanshifu.c",
        ]),
        ([
                "id":          "zhong ling",
                "name":        "钟灵",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/zhongling.c",
        ]),
        ([
                "id":          "bee",
                "name":        "蜜蜂",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/bee.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "挑夫",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/taishan/npc/tiao-fu.c",
        ]),
        ([
                "id":          "ni gu",
                "name":        "尼姑",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/nigu2.c",
        ]),
        ([
                "id":          "ni gu",
                "name":        "尼姑",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/suzhou/npc/nigu1.c",
        ]),
        ([
                "id":          "ban jiu",
                "name":        "斑鸠",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/clone/quarry/niao.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xueshan/npc/xiaoer2.c",
        ]),
        ([
                "id":          "ye tu",
                "name":        "野兔",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/yetu.c",
        ]),
        ([
                "id":          "tufei",
                "name":        "土匪",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wudang/npc/tufei2.c",
        ]),
        ([
                "id":          "wang xiaoer",
                "name":        "王小二",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/village/npc/wang.c",
        ]),
        ([
                "id":          "lao shu",
                "name":        "老鼠",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/ad-laoshu.c",
        ]),
        ([
                "id":          "seller",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/quanzhen/npc/seller.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "家丁",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hanzhong/npc/jiading.c",
        ]),
        ([
                "id":          "dipi",
                "name":        "地痞",
                "type":        "杀",
                "bonus":       48,
                "msg":        "",
                "object":      "/d/hanzhong/npc/dipi.c",
        ]),
        ([
                "id":          "tong",
                "name":        "道童",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/quanzhen/npc/daotong.c",
        ]),
        ([
                "id":          "zhangfang",
                "name":        "帐房先生",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/lingzhou/npc/zhangfang.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/lingzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "wu gong",
                "name":        "[1;31m蜈蚣[2;37;0m",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/huanghe/npc/wugong.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xiangyang/npc/xiaoer2.c",
        ]),
        ([
                "id":          "monkey",
                "name":        "猴子",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wudang/npc/monkey.c",
        ]),
        ([
                "id":          "lao qiao",
                "name":        "乔三槐",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/lao-qiao.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/quanzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "kid",
                "name":        "小孩",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/heimuya/npc/kid.c",
        ]),
        ([
                "id":          "duan tiande",
                "name":        "段天德",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/guiyun/npc/duantiande.c",
        ]),
        ([
                "id":          "xiu cai",
                "name":        "落第秀才",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/guanwai/npc/xiucai.c",
        ]),
        ([
                "id":          "haoshou",
                "name":        "星宿派号手",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/xingxiu/npc/haoshou.c",
        ]),
        ([
                "id":          "xiao tufei",
                "name":        "小土匪",
                "type":        "杀",
                "bonus":       48,
                "msg":        "",
                "object":      "/d/wudang/npc/xiao_tufei.c",
        ]),
        ([
                "id":          "wuya",
                "name":        "乌鸦",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/quanzhou/npc/wuya.c",
        ]),
        ([
                "id":          "sheep",
                "name":        "野羊",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/mingjiao/npc/sheep.c",
        ]),
        ([
                "id":          "zhang",
                "name":        "獐",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/clone/quarry/zhang.c",
        ]),
        ([
                "id":          "wolf dog",
                "name":        "大狼狗",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/wolfdog.c",
        ]),
        ([
                "id":          "lao ban",
                "name":        "酒馆老板",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/guanwai/npc/laoban.c",
        ]),
        ([
                "id":          "seller",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaofan.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/fuzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "zhang chaotang",
                "name":        "张朝唐",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/foshan/npc/zhang.c",
        ]),
        ([
                "id":          "wolf dog",
                "name":        "大狼狗",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/clone/quarry/gou2.c",
        ]),
        ([
                "id":          "shou shangren",
                "name":        "瘦商人",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/foshan/npc/shou.c",
        ]),
        ([
                "id":          "pang shangren",
                "name":        "胖商人",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/foshan/npc/pang.c",
        ]),
        ([
                "id":          "feng qi",
                "name":        "凤七",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/foshan/npc/fengqi.c",
        ]),
        ([
                "id":          "hudie",
                "name":        "蝴蝶",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/yanziwu/npc/hudie.c",
        ]),
        ([
                "id":          "du zhizhu",
                "name":        "[1;34m毒蜘蛛[2;37;0m",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/xuedao/npc/zhizhu.c",
        ]),
        ([
                "id":          "girl",
                "name":        "维吾尔少女",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xingxiu/npc/shaonv.c",
        ]),
        ([
                "id":          "wuya",
                "name":        "乌鸦",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/wuya.c",
        ]),
        ([
                "id":          "little bee",
                "name":        "小蜜蜂",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/little_bee.c",
        ]),
        ([
                "id":          "duck",
                "name":        "野鸭",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/duck.c",
        ]),
        ([
                "id":          "cui hua",
                "name":        "翠花",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/village/npc/cuihua.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-er2.c",
        ]),
        ([
                "id":          "jingxiang ke",
                "name":        "进香客",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiang-ke.c",
        ]),
        ([
                "id":          "jinxiang ke",
                "name":        "进香客",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xueshan/npc/xiang-ke.c",
        ]),
        ([
                "id":          "bee",
                "name":        "蜜蜂",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/bee.c",
        ]),
        ([
                "id":          "monkey",
                "name":        "猴子",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/mingjiao/npc/monkey.c",
        ]),
        ([
                "id":          "wuya",
                "name":        "乌鸦",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/wuya.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "挑夫",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/tiao-fu.c",
        ]),
        ([
                "id":          "qianlong",
                "name":        "乾隆皇帝",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/qianlong.c",
        ]),
        ([
                "id":          "maque",
                "name":        "麻雀",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/maque.c",
        ]),
        ([
                "id":          "liu mang",
                "name":        "流氓",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hangzhou/npc/liumang.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "家丁",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/hangzhou/npc/jiading.c",
        ]),
        ([
                "id":          "girl",
                "name":        "采茶女",
                "type":        "杀",
                "bonus":       47,
                "msg":        "",
                "object":      "/d/hangzhou/npc/caichanu.c",
        ]),
        ([
                "id":          "xiao lama",
                "name":        "小喇嘛",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xuedao/npc/x_lama.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/taishan/npc/xiaoer.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/suzhou/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/suzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "liu mang",
                "name":        "流氓",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/liumang.c",
        ]),
        ([
                "id":          "liu furen",
                "name":        "刘夫人",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/henshan/npc/liufuren.c",
        ]),
        ([
                "id":          "wolf2",
                "name":        "狼",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/heimuya/npc/wolf.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hangzhou/npc/xiaoer.c",
        ]),
        ([
                "id":          "pihuo shang",
                "name":        "皮货商",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/guanwai/npc/pihuoshang.c",
        ]),
        ([
                "id":          "meihua xionglu",
                "name":        "[33m梅花雄鹿[2;37;0m",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/guanwai/npc/buck.c",
        ]),
        ([
                "id":          "gushou",
                "name":        "星宿派鼓手",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/xingxiu/npc/gushou.c",
        ]),
        ([
                "id":          "boshou",
                "name":        "星宿派钹手",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xingxiu/npc/boshou.c",
        ]),
        ([
                "id":          "xiao louluo",
                "name":        "小喽罗",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/xiao_louluo.c",
        ]),
        ([
                "id":          "dog",
                "name":        "野狗",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/clone/quarry/gou.c",
        ]),
        ([
                "id":          "seller",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/suzhou/npc/seller.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/xiao-er.c",
        ]),
        ([
                "id":          "tiao fu",
                "name":        "挑夫",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/shaolin/npc/tiao-fu.c",
        ]),
        ([
                "id":          "lao shu",
                "name":        "老鼠",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/shaolin/npc/ad-laoshu.c",
        ]),
        ([
                "id":          "song shu",
                "name":        "松鼠",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/clone/quarry/song.c",
        ]),
        ([
                "id":          "meihua lu",
                "name":        "梅花鹿",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/clone/quarry/lu.c",
        ]),
        ([
                "id":          "eagle",
                "name":        "秃鹰",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/clone/quarry/ying.c",
        ]),
        ([
                "id":          "woman",
                "name":        "维吾尔族妇女",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/xingxiu/npc/woman.c",
        ]),
        ([
                "id":          "wang yuyan",
                "name":        "王语嫣",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/xiaoyao/npc/wangyuyan.c",
        ]),
        ([
                "id":          "little monkey",
                "name":        "小猴",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/wudang/npc/little_monkey.c",
        ]),
        ([
                "id":          "lai fuer",
                "name":        "来福儿",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/fuer.c",
        ]),
        ([
                "id":          "seller",
                "name":        "小贩",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/village/npc/seller.c",
        ]),
        ([
                "id":          "shu sheng",
                "name":        "书生",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/taishan/npc/shu-sheng.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hanzhong/npc/xiaoer1.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/hanzhong/npc/xiaoer.c",
        ]),
        ([
                "id":          "wu gui",
                "name":        "乌龟",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/hanzhong/npc/wugui.c",
        ]),
        ([
                "id":          "wolf dog",
                "name":        "大狼狗",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/clone/quarry/gou2.c",
        ]),
        ([
                "id":          "chu shi",
                "name":        "厨师",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/meizhuang/npc/chushi.c",
        ]),
        ([
                "id":          "da han",
                "name":        "大汉",
                "type":        "杀",
                "bonus":       60,
                "msg":        "",
                "object":      "/d/huanghe/npc/bangzong.c",
        ]),
        ([
                "id":          "ye tu",
                "name":        "野兔",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/yetu.c",
        ]),
        ([
                "id":          "xue laoban",
                "name":        "薛老板",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/xueboss.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/xiaoer2.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/xiaoer.c",
        ]),
        ([
                "id":          "danding he",
                "name":        "[1;31m丹[2;37;0m顶鹤",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/xianhe.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "乌夷商贩",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/wshangfan.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "台夷商贩",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/dali/npc/tshangfan.c",
        ]),
        ([
                "id":          "tai jian",
                "name":        "太监",
                "type":        "杀",
                "bonus":       90,
                "msg":        "",
                "object":      "/d/dali/npc/taijian.c",
        ]),
        ([
                "id":          "maque",
                "name":        "麻雀",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/maque.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "台夷商贩",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/dali/npc/bshangfan.c",
        ]),
        ([
                "id":          "dufeng",
                "name":        "毒蜂",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/dali/npc/bee.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/chengdu/npc/xiaoer2.c",
        ]),
        ([
                "id":          "yaodian huoji",
                "name":        "药店伙计",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/chengdu/npc/huoji.c",
        ]),
        ([
                "id":          "xiao guizi",
                "name":        "小桂子",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/xiaoguiz.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/city/npc/xiaoer.c",
        ]),
        ([
                "id":          "wolf dog",
                "name":        "大狼狗",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/wolfdog.c",
        ]),
        ([
                "id":          "liu mang",
                "name":        "流氓",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/city/npc/liumang.c",
        ]),
        ([
                "id":          "li apo",
                "name":        "李阿婆",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/city/npc/liapo.c",
        ]),
        ([
                "id":          "jia ding",
                "name":        "家丁",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/city/npc/jiading.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "药铺伙计",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/city/npc/huoji2.c",
        ]),
        ([
                "id":          "yaopu huoji",
                "name":        "药铺伙计",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/city/npc/huoji.c",
        ]),
        ([
                "id":          "xiao hunhun",
                "name":        "小混混",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/city/npc/hunhun.c",
        ]),
        ([
                "id":          "zi yi",
                "name":        "[35m紫衣[2;37;0m",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/ziyi.c",
        ]),
        ([
                "id":          "qing yi",
                "name":        "[1;36m青衣[2;37;0m",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/qingyi.c",
        ]),
        ([
                "id":          "lv yi",
                "name":        "[1;32m绿衣[2;37;0m",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/luyi.c",
        ]),
        ([
                "id":          "lan yi",
                "name":        "[1;34m蓝衣[2;37;0m",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/lanyi.c",
        ]),
        ([
                "id":          "ji nu",
                "name":        "妓女",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/jinu.c",
        ]),
        ([
                "id":          "huang yi",
                "name":        "[1;33m黄衣[2;37;0m",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/huangyi.c",
        ]),
        ([
                "id":          "hong yi",
                "name":        "[1;31m红衣[2;37;0m",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/hongyi.c",
        ]),
        ([
                "id":          "fen yi",
                "name":        "[1;35m粉衣[2;37;0m",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/fenyi.c",
        ]),
        ([
                "id":          "shi jiugong",
                "name":        "时九公",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/doctor.c",
        ]),
        ([
                "id":          "bai yi",
                "name":        "[1;37m白衣[2;37;0m",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/changan/npc/baiyi.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/beijing/npc/xiaoer.c",
        ]),
        ([
                "id":          "du she",
                "name":        "毒蛇",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/beijing/npc/liandan_dushe.c",
        ]),
        ([
                "id":          "xiao er",
                "name":        "店小二",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/baituo/npc/xiaoer.c",
        ]),
        ([
                "id":          "white lady",
                "name":        "白衣少女",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/d/baituo/npc/whitelady.c",
        ]),
        ([
                "id":          "shi wei",
                "name":        "仕卫",
                "type":        "杀",
                "bonus":       76,
                "msg":        "",
                "object":      "/d/baituo/npc/shiwei.c",
        ]),
        ([
                "id":          "xiao shanzei",
                "name":        "小山贼",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/baituo/npc/shanzei1.c",
        ]),
        ([
                "id":          "kid",
                "name":        "小孩",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/baituo/npc/kid.c",
        ]),
        ([
                "id":          "bai tu",
                "name":        "白兔",
                "type":        "杀",
                "bonus":       45,
                "msg":        "",
                "object":      "/d/baituo/npc/baitu.c",
        ]),
        ([
                "id":          "zhao gouer",
                "name":        "赵狗儿",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/zhao-gouer.c",
        ]),
        ([
                "id":          "hong niang",
                "name":        "红娘",
                "type":        "杀",
                "bonus":       50,
                "msg":        "",
                "object":      "/adm/npc/hongniang.c",
        ]),
});
mapping query_questdg()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
string *get_questname()
{
        int i;
        string *result = ({});
        
        for (i = 0; i < sizeof(quest);i ++)
                result += ({ quest[i]["name"] });
                
        return result;
}

