#include <ansi.h>

mapping all_type = ([
        "weapon" : ({ "blade", "club", "hammer", "sword", "staff", "whip", "throwing", "xsword", }),
        "armor"  : ({ "armor", "boots", "cloth", "hands", "finger", "head", "waist", "wrists", "surcoat", }),
        "rings"  : ({ "rings", "neck", "charm", }),
        "gem"    : ({ "gem", }),
]);

string *weapon_type = ({
        "blade", "hammer", "sword", "staff", "whip", "club", "throwing", "xsword",
}); 

string *armor_type = ({
        "armor", "boots", "cloth", "hands", "finger", "head", "waist", "wrists", "surcoat",
});

string *rings_type = ({
        "rings", "neck", "charm",
});

string *item_color = ({
          HIW,         HIB,         HIC,         HIR,         HIM,         HIY,         HIG,
          WHT,         BLU,         CYN,         RED,         MAG,         YEL,         NOR,
});

mapping type_list = ([
        "blade"                :        
                ([
                        "金背大砍刀"        :        "jinbei blade", 
                        "门扇大刀"        :        "menshan blade", 
                        "齐凤朝阳刀"        :        "chaoyang blade",  
                        "象鼻古月刀"        :        "guyue blade",  
                        "砍山刀"        :        "kanshan blade",  
                        "三尖两刃刀"        :        "sanjian blade",  
                        "合扇板门刀"        :        "heshan blade", 
                        "金背砍山刀"        :        "kanshan blade",  
                        "雁翎刀"        :        "yanling blade",  
                        "青铜刀"        :        "qingtong blade",  
                        "丹凤刀"        :        "danfeng blade",  
                        "板门红缨刀"        :        "hongying blade",  
                        "锈绒刀"        :        "xiurong blade",  
                        "七星摺花刀"        :        "qixing blade",  
                        "虎牙刀"        :        "huya blade", 
                        "九耳八环刀"        :        "bahuan blade",  
                        "鱼鳞紫金刀"        :        "yulin blade",  
                        "三叉鬼头刀"        :        "guitou blade",  
                        "亮银刀"        :        "liangyin blade",  
                        "电光刀"        :        "dianguang blade",  
                        "七宝措金刀"        :        "cuojin blade",  
                        "赤铜刀"        :        "chitong blade",  
                        "劈水刀"        :        "pishui blade",  
                        "青钢刀"        :        "qinggang blade", 
                ]),

        "hammer"        :        
                ([
                        "八楞紫金锤"        :        "zijin hammer",   
                        "八楞黄金锤"        :        "huangjin hammer",    
                        "八卦生铜锤"        :        "shengtong hammer",    
                        "八楞亮银锤"        :        "liangyin hammer",    
                        "镔铁轧油锤"        :        "bingtie hammer",    
                        "八卦亮银锤"        :        "bagua hammer",    
                        "擂鼓瓮金锤"        :        "leigu hammer",    
                        "龙头链子锤"        :        "longtou hammer",   
                        "八楞生铁锤"        :        "baleng hammer",    
                        "八卦镔铁锤"        :        "bagua hammer",    
                        "黑虎铜锤"        :        "heihu hammer",    
                        "乌金锤"        :        "wujin hammer",    
                        "压把懒龙锤"        :        "lanlong hammer",    
                        "人面赤铜锤"        :        "chitong hammer",    
                        "瓜梭锤"        :        "guasuo hammer",    
                        "八宝电光锤"        :        "dianguang hammer",    
                        "青铜链子锤"        :        "lianzi hammer",    
                        "电光紫金锤"        :        "zijin hammer",    
                        "八棱铜锤"        :        "baleng hammer",    
                        "浑圆锤"        :        "hunyuan hammer",    
                        "青铜窝瓜锤"        :        "wogua hammer",   
                        "子母鸳鸯锤"        :        "zimu hammer",    
                        "亮银链子锤"        :        "lianzi hammer",    
                        "八角紫金锤"        :        "bajiao hammer",    
                        "红铜锤"        :        "hongtong hammer",    
                        "八宝亮银锤"        :        "babao hammer",    
                ]),
        "sword"                :        
                ([
                        "松纹古定剑"        :        "guding sword",   
                        "七星鎏虹剑"        :        "liuhong sword",    
                        "烈焰青锋剑"        :        "qingfeng sword",    
                        "透龙剑"        :        "toulong sword",    
                        "丧门宝剑"        :        "sanmeng sword",    
                        "紫电青霜剑"        :        "zidian sword",    
                        "紫霜剑"        :        "zishuang sword",    
                        "碧灵剑"        :        "biling sword",    
                        "盘蛇宝剑"        :        "panshe sword",    
                        "盘龙宝剑"        :        "panlong sword",    
                        "天狼剑"        :        "tianlang sword",    
                        "乌钩剑"        :        "wugou sword",    
                        "青钢剑"        :        "qinggang sword",    
                        "鸳鸯剑"        :        "yanyang sword",    
                        "青萍剑"        :        "qingping sword",    
                        "太合剑"        :        "taihe sword",    
                        "日月火龙剑"        :        "huolong sword",    
                        "青龙剑"        :        "qinglong sword",    
                        "诛龙剑"        :        "zhulong sword",    
                        "困龙剑"        :        "kunlong sword",    
                        "寒光剑"        :        "hanguang sword",    
                        "柳叶剑"        :        "liuye sword",    
                        "分天剑"        :        "fentian sword",    
                        "落叶青锋剑"        :        "luoye sword",   
                        "二刃青钢剑"        :        "qinggang sword",    
                        "长虹剑"        :        "changhong sword",   
                        "斩仙剑"        :        "zhanxian sword",    
                        "乌龙剑"        :        "wulong sword",    
                        "青云剑"        :        "qingyun sword",    
                        "梨花宝剑"        :        "lihua sword",    
                        "白光剑"        :        "baiguang sword",    
                        "裁云宝剑"        :        "caiyun sword",    
                ]),
        "staff"                :        
                ([
                        "阴阳杖"        :        "yinyang staff",   
                        "骕濑杖"        :        "lilai staff",  
                        "墨角杖"        :        "mojiao staff",  
                        "牛角杖"        :        "niujiao staff",  
                        "独龙杖"        :        "dulong staff",  
                        "七星卧鱼杖"        :        "woyu staff",  
                        "镔铁丁字杖"        :        "dingzi staff",  
                        "镔铁怀抱杖"        :        "huaibao staff",  
                        "龙头杖"        :        "longtou staff",  
                        "虎头杖"        :        "hutou staff", 
                        "七星杖"        :        "qixing staff",  
                        "护手双铁杖"        :        "hushou staff",  
                        "鸳鸯杖"        :        "yanyang staff",  
                        "单刀卧鱼杖"        :        "woyu staff",  
                        "沉香杖"        :        "chenxiang staff",  
                        "勾搂虎头杖"        :        "goulou staff",  
                        "镔铁鸳鸯杖"        :        "yanyang staff", 
                ]),
        "club"                :        
                ([
                        "水火囚龙棒"        :        "qiulong club",   
                        "开山棒"        :        "kaishan club", 
                        "钉钉狼牙棒"        :        "dingding club", 
                        "渗金蒺藜棒"        :        "shenjin club", 
                        "紫金虬龙棒"        :        "zijin club", 
                        "乌油棒"        :        "wuyou club", 
                        "八棱棒"        :        "baleng club", 
                        "龙头软棒"        :        "longtou club", 
                        "浑铁棒"        :        "huntie club", 
                        "天罡棒"        :        "tiangang club", 
                        "独龙渗金棒"        :        "dulong club", 
                        "行者棒"        :        "xingzhe club", 
                        "亮银狼牙棒"        :        "langya club", 
                        "青铜蒺藜棒"        :        "qingtong club", 
                        "镔铁螺丝棒"        :        "luosi club", 
                        "金丝藤蛇棒"        :        "tengshe club", 
                        "金光狼牙棒"        :        "jinguang club", 
                        "百钉狼牙棒"        :        "baiding club", 
                        "紫藤软棒"        :        "ziteng club", 
                        "青铜棒槌"        :        "qingtong club", 
                        "金丝棒槌"        :        "jinsi club",
                ]),
        "whip"                :        
                ([
                        "亮银鞭"        :        "liangyin whip",
                        "竹节钢鞭"        :        "zhujie whip",
                        "豹尾鞭"        :        "baowei whip", 
                        "打将鞭"        :        "dajiang whip", 
                        "驼骨阴风鞭"        :        "tuogu whip", 
                        "金龙鞭"        :        "jinlong whip", 
                        "虎尾钢鞭"        :        "huwei whip", 
                        "镔铁鞭"        :        "bingtie whip", 
                        "龙头凤尾鞭"        :        "longtou whip", 
                        "虎眼钢鞭"        :        "huyan whip", 
                        "金丝软鞭"        :        "jinsi whip", 
                        "葫芦鞭"        :        "hulu whip", 
                        "龟骨鞭"        :        "guigu whip", 
                        "鱼尾鞭"        :        "yugu whip", 
                        "蛇骨鞭"        :        "shegu whip", 
                        "银丝软鞭"        :        "yinsi whip", 
                        "遮云扫龙鞭"        :        "zheyun whip", 
                ]),

        "cloth"                :        
                ([
                        "麻布衣"        :        "mabu cloth",
                        "棉布衣"        :        "mianbu cloth",
                        "绸布衣"        :        "choubu cloth",
                        "飞雪衣"        :        "feixue cloth",
                        "夜魔衣"        :        "yemo cloth",
                        "青丝衣"        :        "qingsi cloth",
                        "九天袍"        :        "jiutian cloth",
                        "虚无袍"        :        "xuwu cloth",
                        "青冥袍"        :        "qingming cloth",
                        "云罗衣"        :        "yunluo cloth",
                        "丝绸长袍"        :        "silk cloth",
                ]),
        "head"                :        
                ([
                        "闹龙垂头"        :        "naolong kui",
                        "夜明盔"        :        "yeming kui",
                        "凤翅金盔"        :        "fengchi kui",
                        "铜荷叶盔"        :        "heye kui",
                        "黄金帅字盔"        :        "huangjin kui", 
                        "银练盔"        :        "yinlian kui",
                        "分水盔"        :        "fenshui kui",
                        "五凤朝阳盔"        :        "chaoyang kui", 
                        "凤翅月明盔"        :        "fengchi kui", 
                        "狼牙盔"        :        "langya kui", 
                        "五凤花盔"        :        "wufeng kui", 
                        "太岁盔"        :        "taisui kui", 
                        "钻天盔"        :        "zuantian kui",
                        "亮银虎头盔"        :        "hutou kui", 
                        "豹子盔"        :        "baozi kui", 
                        "蝴蝶金盔"        :        "hudie kui", 
                        "双凤冠"        :        "shuangfeng guan", 
                        "金凤冠"        :        "jinfeng guan",  
                        "赤金冠"        :        "chijin guan",  
                        "金霞冠"        :        "jinxia guan", 
                        "紫金冠"        :        "zijin guan",  
                        "束发金冠"        :        "shufa guan",  
                        "九云烈焰冠"        :        "lieyan guan", 
                ]),
        "neck"                :        
                ([
                        "黑狐颈链"        :        "heihu necklace",
                        "女神颈链"        :        "nvshen necklace",
                        "银项链"        :        "yin necklace",
                        "铜项链"        :        "tong necklace",
                        "金项链"        :        "jin necklace",
                        "蓝玉项链"        :        "lanyu necklace",
                        "黄水晶项链"        :        "shuijing necklace",
                        "青铜项链"        :        "qingtong necklace",
                        "葱头项链"        :        "congtou necklace",
                        "骷髅项链"        :        "kulou necklace",
                        "古树项链"        :        "gushu necklace",
                        "翡翠项链"        :        "feicui necklace",
                        "冰鳞项链"        :        "binglin necklace",
                ]),
        "armor"                :
                ([
                        "柳叶绵竹铠"        :        "liuye armor",
                        "大叶鱼鳞甲"        :        "yulin armor",
                        "大叶龙鳞甲"        :        "longlin armor",
                        "镔铁甲"        :        "bingtie armor", 
                        "赤金铠甲"        :        "chijin armor", 
                        "黄金甲"        :        "huangjin armor",
                        "龟背甲"        :        "guibei armor",
                        "墨鱼甲"        :        "moyu armor",
                        "赤铜大叶甲"        :        "chitong armor",
                        "银装甲"        :        "yinzhuang armor", 
                        "连环镔铁铠"        :        "lianhuan armor",
                        "月落红云甲"        :        "yueluo armor",
                        "金丝软甲"        :        "jinsi armor",
                        "紫藤甲"        :        "ziteng armor",
                        "紫金护心甲"        :        "huxin armor", 
                        "荷叶连环甲"        :        "heye armor", 
                ]),
        "surcoat"        :        
                ([
                        "夜光披风"        :        "yeguang pifeng",
                        "黄金披风"        :        "huangjin pifeng",
                        "绵布斗篷"        :        "mianbu pifeng",
                        "羊皮斗篷"        :        "yangpi pifeng",
                        "绸缎斗篷"        :        "chouduan pifeng",
                        "赤红斗篷"        :        "chihong pifeng",
                        "灵角披风"        :        "lingjiao pifeng",
                        "战月披风"        :        "zhanyue pifeng",
                        "异兽披风"        :        "yishou pifeng",
                ]),
        "waist"                :        
                ([
                        "帆布腰带"        :        "fanbu waist",
                        "真皮腰带"        :        "zhenpi waist",
                        "编织腰带"        :        "bianzhi waist",
                        "粗布腰带"        :        "cubu waist",
                        "生铁腰带"        :        "shengtie waist",
                        "琥珀腰带"        :        "hupo waist",
                        "冰鳞腰带"        :        "binglin waist",
                        "白银腰带"        :        "baiying waist",
                        "翡翠腰带"        :        "feicui waist",
                ]),
        "wrists"        :        
                ([
                        "粗布护腕"        :        "cubu wrists",
                        "紫竹护腕"        :        "zizhu wrists",
                        "古木护腕"        :        "gumu wrists",
                        "青铜护腕"        :        "qingtong wrists",
                        "精铁护腕"        :        "jingtie wrists",
                        "翡翠护腕"        :        "feicui wrists",
                        "黄金护腕"        :        "huangjin wrists",
                        "冰鳞护腕"        :        "bingling wrists",
                ]),
        "finger"        :
                ([
                        "永恒戒指"        :        "yongheng ring",
                        "花戒指"        :        "hua ring",
                        "银戒指"        :        "yin ring",
                        "威严戒指"        :        "weiyan ring",
                        "首领戒指"        :        "shouling ring",
                        "古树戒指"        :        "gushu ring",
                        "隐士戒指"        :        "yinshi ring",
                        "十字骨戒"        :        "shizi ring",
                        "水晶戒指"        :        "shuijing ring",
                        "冰鳞戒指"        :        "bingling ring",
                        "翡翠戒指"        :        "feicui ring",
                        "飞雪戒指"        :        "feixue ring",
                        "紫竹戒指"        :        "zizhu ring",
                        "兽骨戒指"        :        "shougu ring",
                ]),
        "hands"                :        
                ([
                        "流云手套"        :        "liuyun glove",
                        "赤炼手套"        :        "chilian glove",
                        "虚无手套"        :        "xuwu glove",
                        "镏金手套"        :        "liujin glove",
                        "镔铁手套"        :        "bingtie glove",
                ]),
        "boots"                :        
                ([
                        "流云靴"        :        "liuyun shoes",
                        "赤炼靴"        :        "chilian shoes",
                        "虚无靴"        :        "xuwu shoes",
                        "镏金靴"        :        "liujin shoes",
                        "火龙靴"        :        "huolong shoes",
                        "兽皮靴"        :        "shoupi shoes",
                        "铜牙靴"        :        "tongya shoes",
                        "精铁靴"        :        "jingtie shoes",
                        "乘风靴"        :        "chengfeng shoes",
                        "虎纹靴"        :        "huwen shoes",
                        "破浪靴"        :        "polang shoes",
                ]),
]);
