#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "yu zu",
                "name":        "狱卒",
                "type":        "杀",
                "bonus":       110,
                "msg":        "",
                "object":      "/d/shaolin/npc/yu-zu.c",
        ]),
        ([
                "id":          "lin pingzhi",
                "name":        "林平之",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/huashan/npc/lin-pingzhi.c",
        ]),
        ([
                "id":          "yu canghai",
                "name":        "余沧海",
                "type":        "杀",
                "bonus":       66,
                "msg":        "",
                "object":      "/kungfu/class/qingcheng/yu.c",
        ]),
        ([
                "id":          "feng xifan",
                "name":        "冯锡范",
                "type":        "杀",
                "bonus":       106,
                "msg":        "",
                "object":      "/d/guanwai/npc/fengxifan.c",
        ]),
        ([
                "id":          "zhao banshan",
                "name":        "赵半山",
                "type":        "杀",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/zhao.c",
        ]),
        ([
                "id":          "wuchen daozhang",
                "name":        "无尘道长",
                "type":        "杀",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/hangzhou/honghua/wuchen.c",
        ]),
        ([
                "id":          "zhang chengyun",
                "name":        "张乘云",
                "type":        "杀",
                "bonus":       106,
                "msg":        "",
                "object":      "/d/heimuya/npc/zhang2.c",
        ]),
        ([
                "id":          "zhao he",
                "name":        "赵鹤",
                "type":        "杀",
                "bonus":       106,
                "msg":        "",
                "object":      "/d/heimuya/npc/zhaohe.c",
        ]),
        ([
                "id":          "fan song",
                "name":        "范松",
                "type":        "杀",
                "bonus":       106,
                "msg":        "",
                "object":      "/d/heimuya/npc/fansong.c",
        ]),
        ([
                "id":          "cong buqi",
                "name":        "丛不弃",
                "type":        "杀",
                "bonus":       73,
                "msg":        "",
                "object":      "/kungfu/class/huashan/cong-buqi.c",
        ]),
        ([
                "id":          "cheng buyou",
                "name":        "成不忧",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/huashan/cheng-buyou.c",
        ]),
        ([
                "id":          "taoshi xian",
                "name":        "桃实仙",
                "type":        "杀",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao6.c",
        ]),
        ([
                "id":          "taohua xian",
                "name":        "桃花仙",
                "type":        "杀",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao5.c",
        ]),
        ([
                "id":          "taoye xian",
                "name":        "桃叶仙",
                "type":        "杀",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao4.c",
        ]),
        ([
                "id":          "taozhi xian",
                "name":        "桃枝仙",
                "type":        "杀",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao3.c",
        ]),
        ([
                "id":          "taogan xian",
                "name":        "桃干仙",
                "type":        "杀",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao2.c",
        ]),
        ([
                "id":          "taogen xian",
                "name":        "桃根仙",
                "type":        "杀",
                "bonus":       77,
                "msg":        "",
                "object":      "/d/city/npc/tao1.c",
        ]),
        ([
                "id":          "qu lingfeng",
                "name":        "曲三",
                "type":        "杀",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/taohua/qu.c",
        ]),
        ([
                "id":          "xu xueting",
                "name":        "许雪亭",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/shenlong/xu.c",
        ]),
        ([
                "id":          "peng youjing",
                "name":        "彭有敬",
                "type":        "杀",
                "bonus":       69,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/peng.c",
        ]),
        ([
                "id":          "liang zhanglao",
                "name":        "梁长老",
                "type":        "杀",
                "bonus":       89,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/liang.c",
        ]),
        ([
                "id":          "jian zhanglao",
                "name":        "简长老",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/jian.c",
        ]),
        ([
                "id":          "duan yu",
                "name":        "段誉",
                "type":        "杀",
                "bonus":       106,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyu.c",
        ]),
        ([
                "id":          "xiang wentian",
                "name":        "向问天",
                "type":        "杀",
                "bonus":       85,
                "msg":        "",
                "object":      "/d/heimuya/npc/xiang.c",
        ]),
        ([
                "id":          "miao renfeng",
                "name":        "苗人凤",
                "type":        "杀",
                "bonus":       82,
                "msg":        "",
                "object":      "/d/shaolin/npc/miao.c",
        ]),
        ([
                "id":          "ren woxing",
                "name":        "任我行",
                "type":        "杀",
                "bonus":       80,
                "msg":        "",
                "object":      "/d/heimuya/npc/renwoxing.c",
        ]),
        ([
                "id":          "zuo lengchan",
                "name":        "左冷禅",
                "type":        "杀",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/songshan/zuo.c",
        ]),
        ([
                "id":          "feng xifan",
                "name":        "冯锡范",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/guanwai/npc/fengxifan.c",
        ]),
        ([
                "id":          "wen cangsong",
                "name":        "闻苍松",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/mingjiao/npc/wensong.c",
        ]),
        ([
                "id":          "zhang chengyun",
                "name":        "张乘云",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/heimuya/npc/zhang2.c",
        ]),
        ([
                "id":          "zhao he",
                "name":        "赵鹤",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/heimuya/npc/zhaohe.c",
        ]),
        ([
                "id":          "yue nv",
                "name":        "越女",
                "type":        "杀",
                "bonus":       85,
                "msg":        "",
                "object":      "/d/hangzhou/npc/yuenv.c",
        ]),
        ([
                "id":          "fan song",
                "name":        "范松",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/heimuya/npc/fansong.c",
        ]),
        ([
                "id":          "murong fu",
                "name":        "慕容复",
                "type":        "杀",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/murong/murongfu.c",
        ]),
        ([
                "id":          "murong longcheng",
                "name":        "慕容龙城",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/murong/longcheng.c",
        ]),
        ([
                "id":          "zhuo bufan",
                "name":        "卓不凡",
                "type":        "杀",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/lingjiu/zhuo.c",
        ]),
        ([
                "id":          "hu yizhi",
                "name":        "胡逸之",
                "type":        "杀",
                "bonus":       77,
                "msg":        "",
                "object":      "/kungfu/class/hu/huyizhi.c",
        ]),
        ([
                "id":          "yang guo",
                "name":        "杨过",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/kungfu/class/gumu/yang.c",
        ]),
        ([
                "id":          "jinlun fawang",
                "name":        "金轮法王",
                "type":        "杀",
                "bonus":       84,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/fawang.c",
        ]),
        ([
                "id":          "hong antong",
                "name":        "洪安通",
                "type":        "杀",
                "bonus":       82,
                "msg":        "",
                "object":      "/kungfu/class/shenlong/hong.c",
        ]),
        ([
                "id":          "du nan",
                "name":        "渡难",
                "type":        "杀",
                "bonus":       85,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-nan.c",
        ]),
        ([
                "id":          "du jie",
                "name":        "渡劫",
                "type":        "杀",
                "bonus":       83,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-jie.c",
        ]),
        ([
                "id":          "du e",
                "name":        "渡厄",
                "type":        "杀",
                "bonus":       84,
                "msg":        "",
                "object":      "/kungfu/class/shaolin/du-e.c",
        ]),
        ([
                "id":          "lin chaoying",
                "name":        "林朝英",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/kungfu/class/gumu/lin.c",
        ]),
        ([
                "id":          "duan yu",
                "name":        "段誉",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyu.c",
        ]),
        ([
                "id":          "duan yanqing",
                "name":        "段延庆",
                "type":        "杀",
                "bonus":       78,
                "msg":        "",
                "object":      "/kungfu/class/duan/duanyq.c",
        ]),
        ([
                "id":          "shanzei tou",
                "name":        "山贼头",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/baituo/npc/shanzei3.c",
        ]),
        ([
                "id":          "jiuyi daoren",
                "name":        "九翼道人",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/lingjiu/npc/jiuyi.c",
        ]),
        ([
                "id":          "wu santong",
                "name":        "武三通",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wusantong.c",
        ]),
        ([
                "id":          "wang bashuai",
                "name":        "王八衰",
                "type":        "杀",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/wang8.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "媒婆",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/suzhou/npc/meipo.c",
        ]),
        ([
                "id":          "sha tianjiang",
                "name":        "沙天江",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/songshan/npc/sha.c",
        ]),
        ([
                "id":          "yue lingshan",
                "name":        "岳灵珊",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huashan/npc/yue-lingshan.c",
        ]),
        ([
                "id":          "hou tonghai",
                "name":        "侯通海",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huanghe/npc/hou.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "白衣武士",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi1.c",
        ]),
        ([
                "id":          "di xiu",
                "name":        "狄修",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/kungfu/class/songshan/di.c",
        ]),
        ([
                "id":          "yu renhao",
                "name":        "于人豪",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/yu.c",
        ]),
        ([
                "id":          "san hu",
                "name":        "忽伦三虎",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sanhu.c",
        ]),
        ([
                "id":          "jiao wenqi",
                "name":        "焦文期",
                "type":        "杀",
                "bonus":       99,
                "msg":        "",
                "object":      "/d/guanwai/npc/jiaowenqi.c",
        ]),
        ([
                "id":          "zu qianqiu",
                "name":        "祖千秋",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/huanghe/npc/zu.c",
        ]),
        ([
                "id":          "er hu",
                "name":        "忽伦二虎",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/erhu.c",
        ]),
        ([
                "id":          "da hu",
                "name":        "忽伦大虎",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/dahu.c",
        ]),
        ([
                "id":          "bo chen",
                "name":        "卜沉",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/songshan/npc/bo.c",
        ]),
        ([
                "id":          "lao denuo",
                "name":        "劳德诺",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/huashan/npc/lao-denuo.c",
        ]),
        ([
                "id":          "sun popo",
                "name":        "孙婆婆",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/gumu/npc/sun.c",
        ]),
        ([
                "id":          "hong renxiong",
                "name":        "洪人雄",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/hong.c",
        ]),
        ([
                "id":          "song qingshu",
                "name":        "宋青书",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/emei/npc/songqingshu.c",
        ]),
        ([
                "id":          "wu xiuwen",
                "name":        "武修文",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/xiangyang/npc/wuxiuwen.c",
        ]),
        ([
                "id":          "zhou wushu",
                "name":        "周五输",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhou5.c",
        ]),
        ([
                "id":          "zheng qimie",
                "name":        "郑七灭",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zheng7.c",
        ]),
        ([
                "id":          "lu bai",
                "name":        "陆柏",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/songshan/npc/lu.c",
        ]),
        ([
                "id":          "gao kexin",
                "name":        "高克新",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/songshan/npc/gao.c",
        ]),
        ([
                "id":          "sun sanhui",
                "name":        "孙三毁",
                "type":        "杀",
                "bonus":       65,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/sun3.c",
        ]),
        ([
                "id":          "yuji zi",
                "name":        "玉玑子",
                "type":        "杀",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yujizi.c",
        ]),
        ([
                "id":          "zhong zhen",
                "name":        "钟镇",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/songshan/npc/zhong.c",
        ]),
        ([
                "id":          "luo renjie",
                "name":        "罗人杰",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/luo.c",
        ]),
        ([
                "id":          "zhu ziliu",
                "name":        "朱子柳",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/xiangyang/npc/zhuziliu.c",
        ]),
        ([
                "id":          "wei shi",
                "name":        "红衣武士",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/taishan/npc/wei-shi2.c",
        ]),
        ([
                "id":          "li kexiu",
                "name":        "李可秀",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/hangzhou/npc/likexiu.c",
        ]),
        ([
                "id":          "si hu",
                "name":        "忽伦四虎",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/guanwai/npc/sihu.c",
        ]),
        ([
                "id":          "yuqing zi",
                "name":        "玉磬子",
                "type":        "杀",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yuqingzi.c",
        ]),
        ([
                "id":          "ding mian",
                "name":        "丁勉",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/songshan/npc/ding.c",
        ]),
        ([
                "id":          "huo renying",
                "name":        "侯人英",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/qingcheng/npc/hou.c",
        ]),
        ([
                "id":          "hu qingniu",
                "name":        "胡青牛",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/mingjiao/npc/hu.c",
        ]),
        ([
                "id":          "li si",
                "name":        "李四",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/village/npc/xiejian.c",
        ]),
        ([
                "id":          "zhao yishang",
                "name":        "赵一伤",
                "type":        "杀",
                "bonus":       62,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/zhao1.c",
        ]),
        ([
                "id":          "li sicui",
                "name":        "李四摧",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/tulong/yitian/npc/li4.c",
        ]),
        ([
                "id":          "yuyin zi",
                "name":        "玉音子",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/taishan/yuyinzi.c",
        ]),
        ([
                "id":          "tang yinghu",
                "name":        "汤英鹄",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/d/songshan/npc/tang.c",
        ]),
        ([
                "id":          "ping si",
                "name":        "平四",
                "type":        "杀",
                "bonus":       91,
                "msg":        "",
                "object":      "/kungfu/class/hu/pingsi.c",
        ]),
        ([
                "id":          "huo xiansheng",
                "name":        "霍先生",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/dali/npc/huo.c",
        ]),
        ([
                "id":          "yulin jun",
                "name":        "御林军",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/d/changan/npc/yulinjun.c",
        ]),
        ([
                "id":          "wu jiang",
                "name":        "武将",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/d/changan/npc/wujiang.c",
        ]),
        ([
                "id":          "murong hao",
                "name":        "慕容豪",
                "type":        "杀",
                "bonus":       67,
                "msg":        "",
                "object":      "/d/changan/npc/murong-hao.c",
        ]),
        ([
                "id":          "da shou",
                "name":        "打手",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/dashou.c",
        ]),
        ([
                "id":          "bao biao",
                "name":        "群玉楼保镖",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/changan/npc/baobiao.c",
        ]),
        ([
                "id":          "gongtangcang guoshi",
                "name":        "贡唐仓国师",
                "type":        "杀",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/xueshan/guoshi.c",
        ]),
        ([
                "id":          "shan yong",
                "name":        "善勇",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/kungfu/class/xuedao/shanyong.c",
        ]),
        ([
                "id":          "xue muhua",
                "name":        "薛慕华",
                "type":        "杀",
                "bonus":       79,
                "msg":        "",
                "object":      "/kungfu/class/xiaoyao/xuemuh.c",
        ]),
        ([
                "id":          "zhao zhijing",
                "name":        "赵志敬",
                "type":        "杀",
                "bonus":       95,
                "msg":        "",
                "object":      "/kungfu/class/quanzhen/zhao.c",
        ]),
        ([
                "id":          "kuai huosan",
                "name":        "快活三",
                "type":        "杀",
                "bonus":       63,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/kuai-huosan.c",
        ]),
        ([
                "id":          "jiang shangyou",
                "name":        "江上游",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/jiang-sy.c",
        ]),
        ([
                "id":          "meipo",
                "name":        "媒婆",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/adm/npc/meipo.c",
        ]),
});
mapping query_questsn()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
