#include <ansi.h>

mapping *quest = ({
        ([
                "id":          "jin xier",
                "name":        "进喜儿",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/xier.c",
        ]),
        ([
                "id":          "shu tong",
                "name":        "书童",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/guiyun/npc/shutong.c",
        ]),
        ([
                "id":          "mengmian ren",
                "name":        "蒙面人",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/xiaoyao/npc/mengmianr.c",
        ]),
        ([
                "id":          "piao you",
                "name":        "票友",
                "type":        "杀",
                "bonus":       71,
                "msg":        "",
                "object":      "/d/suzhou/npc/piaoyou.c",
        ]),
        ([
                "id":          "wu qinglie",
                "name":        "吴青烈",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/huanghe/npc/wu.c",
        ]),
        ([
                "id":          "guan jia",
                "name":        "管家",
                "type":        "杀",
                "bonus":       58,
                "msg":        "",
                "object":      "/d/henshan/npc/guanjia.c",
        ]),
        ([
                "id":          "jian ke",
                "name":        "剑客",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/hangzhou/npc/jian-ke.c",
        ]),
        ([
                "id":          "dao ke",
                "name":        "刀客",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/hangzhou/npc/dao-ke.c",
        ]),
        ([
                "id":          "chen qi",
                "name":        "陈七",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/fuzhou/npc/chenqi.c",
        ]),
        ([
                "id":          "bai er",
                "name":        "白二",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/fuzhou/npc/baier.c",
        ]),
        ([
                "id":          "huogong",
                "name":        "火工道人",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/quanzhen/npc/huogong.c",
        ]),
        ([
                "id":          "shi nu",
                "name":        "慌张的侍女",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/heimuya/npc/shinu1.c",
        ]),
        ([
                "id":          "tufei",
                "name":        "土匪",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/wudang/npc/tufei2.c",
        ]),
        ([
                "id":          "wang xiaoer",
                "name":        "王小二",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/village/npc/wang.c",
        ]),
        ([
                "id":          "guan jia",
                "name":        "管家",
                "type":        "杀",
                "bonus":       58,
                "msg":        "",
                "object":      "/d/hanzhong/npc/guanjia.c",
        ]),
        ([
                "id":          "qian qingjian",
                "name":        "钱青健",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/huanghe/npc/qian.c",
        ]),
        ([
                "id":          "monkey",
                "name":        "猴子",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/wudang/npc/monkey.c",
        ]),
        ([
                "id":          "jian ke",
                "name":        "剑客",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/taishan/npc/jian-ke.c",
        ]),
        ([
                "id":          "sheep",
                "name":        "野羊",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/mingjiao/npc/sheep.c",
        ]),
        ([
                "id":          "qing bing",
                "name":        "绿营清兵",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/hangzhou/npc/qingbing.c",
        ]),
        ([
                "id":          "seng bing",
                "name":        "守寺僧兵",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/xueshan/npc/seng-bing1.c",
        ]),
        ([
                "id":          "tufei",
                "name":        "土匪",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/wudang/npc/tufei1.c",
        ]),
        ([
                "id":          "cheng ying",
                "name":        "程英",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/taohua/npc/cheng.c",
        ]),
        ([
                "id":          "dao ke",
                "name":        "刀客",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/taishan/npc/dao-ke.c",
        ]),
        ([
                "id":          "dizi",
                "name":        "弟子",
                "type":        "杀",
                "bonus":       70,
                "msg":        "",
                "object":      "/d/shenlong/npc/dizi.c",
        ]),
        ([
                "id":          "young boy",
                "name":        "年轻弟子",
                "type":        "杀",
                "bonus":       88,
                "msg":        "",
                "object":      "/d/shenlong/npc/boy2.c",
        ]),
        ([
                "id":          "hai gonggong",
                "name":        "海公公",
                "type":        "杀",
                "bonus":       75,
                "msg":        "",
                "object":      "/d/quanzhou/npc/hai.c",
        ]),
        ([
                "id":          "yu zu",
                "name":        "狱卒",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/shaolin/npc/yu-zu.c",
        ]),
        ([
                "id":          "monkey",
                "name":        "猴子",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/mingjiao/npc/monkey.c",
        ]),
        ([
                "id":          "shi nu",
                "name":        "侍女",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/heimuya/npc/shinu.c",
        ]),
        ([
                "id":          "dizi",
                "name":        "成德殿殿下弟子",
                "type":        "杀",
                "bonus":       54,
                "msg":        "",
                "object":      "/d/heimuya/npc/dizi.c",
        ]),
        ([
                "id":          "liumang tou",
                "name":        "流氓头",
                "type":        "杀",
                "bonus":       56,
                "msg":        "",
                "object":      "/d/hangzhou/npc/liumangtou.c",
        ]),
        ([
                "id":          "shen qinggang",
                "name":        "沈青刚",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/huanghe/npc/shen.c",
        ]),
        ([
                "id":          "wolf2",
                "name":        "狼",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/heimuya/npc/wolf.c",
        ]),
        ([
                "id":          "guan jia",
                "name":        "管家",
                "type":        "杀",
                "bonus":       58,
                "msg":        "",
                "object":      "/d/hangzhou/npc/guanjia.c",
        ]),
        ([
                "id":          "pihuo shang",
                "name":        "皮货商",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/guanwai/npc/pihuoshang.c",
        ]),
        ([
                "id":          "tufei tou",
                "name":        "土匪头",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/wudang/npc/tufeitou.c",
        ]),
        ([
                "id":          "wushi",
                "name":        "巫士",
                "type":        "杀",
                "bonus":       54,
                "msg":        "",
                "object":      "/d/mingjiao/npc/miaozuwushi.c",
        ]),
        ([
                "id":          "menmian ren",
                "name":        "蒙面人",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/huanghe/npc/menmian.c",
        ]),
        ([
                "id":          "ma qingxiong",
                "name":        "马青雄",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/huanghe/npc/ma.c",
        ]),
        ([
                "id":          "lai fuer",
                "name":        "来福儿",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/wanjiegu/npc/fuer.c",
        ]),
        ([
                "id":          "tangzi shou",
                "name":        "趟子手",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/taishan/npc/tangzi.c",
        ]),
        ([
                "id":          "hou yuanwai",
                "name":        "侯员外",
                "type":        "杀",
                "bonus":       68,
                "msg":        "",
                "object":      "/d/hanzhong/npc/yuanwai.c",
        ]),
        ([
                "id":          "shang fan",
                "name":        "乌夷商贩",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/dali/npc/wshangfan.c",
        ]),
        ([
                "id":          "tai jian",
                "name":        "太监",
                "type":        "杀",
                "bonus":       52,
                "msg":        "",
                "object":      "/d/dali/npc/taijian.c",
        ]),
        ([
                "id":          "ke shang",
                "name":        "盛皮罗客商",
                "type":        "杀",
                "bonus":       56,
                "msg":        "",
                "object":      "/d/dali/npc/keshang.c",
        ]),
        ([
                "id":          "e nu",
                "name":        "恶奴",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/dali/npc/enu.c",
        ]),
        ([
                "id":          "xiao zei",
                "name":        "小贼",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/chengdu/npc/xiaozei.c",
        ]),
        ([
                "id":          "liumang tou",
                "name":        "流氓头",
                "type":        "杀",
                "bonus":       56,
                "msg":        "",
                "object":      "/d/city/npc/liumangtou.c",
        ]),
        ([
                "id":          "wang wu",
                "name":        "王五",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/city/npc/guidao.c",
        ]),
        ([
                "id":          "guan jia",
                "name":        "管家",
                "type":        "杀",
                "bonus":       58,
                "msg":        "",
                "object":      "/d/city/npc/guanjia.c",
        ]),
        ([
                "id":          "xi zi",
                "name":        "戏子",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/changan/npc/xizi.c",
        ]),
        ([
                "id":          "lao zhang",
                "name":        "老张",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/changan/npc/laozhang.c",
        ]),
        ([
                "id":          "shuoshu laoren",
                "name":        "说书老人",
                "type":        "杀",
                "bonus":       54,
                "msg":        "",
                "object":      "/d/changan/npc/laoren.c",
        ]),
        ([
                "id":          "guan jia",
                "name":        "管家",
                "type":        "杀",
                "bonus":       61,
                "msg":        "",
                "object":      "/d/changan/npc/guanjia.c",
        ]),
        ([
                "id":          "wolf",
                "name":        "野狼",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/baituo/npc/wolf.c",
        ]),
        ([
                "id":          "shan zei",
                "name":        "山贼",
                "type":        "杀",
                "bonus":       66,
                "msg":        "",
                "object":      "/d/baituo/npc/shanzei2.c",
        ]),
        ([
                "id":          "lao cai",
                "name":        "老材",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/baituo/npc/laocai.c",
        ]),
        ([
                "id":          "guan jia",
                "name":        "管家",
                "type":        "杀",
                "bonus":       87,
                "msg":        "",
                "object":      "/d/baituo/npc/guanjia.c",
        ]),
        ([
                "id":          "guafu",
                "name":        "寡妇",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/baituo/npc/guafu.c",
        ]),
        ([
                "id":          "fox",
                "name":        "狐狸",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/baituo/npc/fox.c",
        ]),
        ([
                "id":          "fei fei",
                "name":        "厨师",
                "type":        "杀",
                "bonus":       64,
                "msg":        "",
                "object":      "/d/baituo/npc/feifei.c",
        ]),
        ([
                "id":          "qiu wanjia",
                "name":        "裘万家",
                "type":        "杀",
                "bonus":       68,
                "msg":        "",
                "object":      "/kungfu/class/gaibang/qiu-wanjia.c",
        ]),
});
mapping query_questsn()
{
        int i;
        mapping the_quest,random_quest;
        string *quest_key;

        random_quest = quest[random(sizeof(quest))];
        the_quest = ([]);

        quest_key = keys(random_quest);
        for (i = 0;i < sizeof(quest_key);i++)
                the_quest[quest_key[i]] = random_quest[quest_key[i]];

        return the_quest;
}
